---
# Installs necessary software

- name: "Set up directory for Java"
  file: state=directory path=/usr/java

- name: "Download JDK"
  get_url:
    url: http://dist/storage/JDK/jdk-{{JDK_VERSION}}-linux-x64.tar.gz
    dest: /tmp/jdk-{{JDK_VERSION}}-linux-x64.tar.gz
    checksum: md5:{{JDK_CHECKSUM}}

- name: "Extract JDK"
  unarchive:
   remote_src: yes
   src: /tmp/jdk-{{JDK_VERSION}}-linux-x64.tar.gz
   dest: /usr/java
   owner: root
   group: root

# Sometimes cancelled ansible playbooks can leave yum with
# pending transactions which cause yum module based install
# to fail.
- name: "Ensure that there are no pending yum transactions"
  command: yum-complete-transaction --cleanup-only

- name: "Uninstall ABRT package due to conflicts with Scylla"
  yum: name=abrt state=absent

# Use ToolsV2 repo instead of Scylla's public repo
# Ansible yum module does not support --disableexcludes
- name: "Install Scylla"
  command: yum --disableexcludes=ToolsV2 install -y {{item}}
  with_items:
    - scylla-{{SCYLLA_VERSION}}
    - scylla-debuginfo-{{SCYLLA_VERSION}}

- name: "Install Telegraf"
  yum: name=telegraf-qubit-scylla state=present

- name: "Select Oracle JDK"
  alternatives: link=/usr/bin/java name=java path=/usr/java/jdk{{JDK_VER_DIR}}/bin/java

# install Scylla repair script dependencies
- name: "Install python2 pip"
  command: easy_install-2.7 pip

- name: "Install Tinydb"
  command: pip2 install tinydb
...
