#!/usr/bin/env python
# Copyright (c) 2016 Arista Networks, Inc.  All rights reserved.
# Arista Networks, Inc. Confidential and Proprietary.

# Wrapper script for "restore_server"

# Scan servers table for "verify_ready" servers
# Get all of the servers and call "restore_server sv1 sv2 sv3 sv4..."

import MySQLdb
import subprocess

#TODO make shared library for this to share with 
# Database information
#DB_INFO = { "user": "arastra",
#            "db": "datacenter",
#            "host": "mysql-b1.cs2.aristanetworks.com" }

# Datatable to read from
#SERV_DB = "servers"
#PROP_DB = "server_property"

#def main():
   


if __name__ == "__main__":
   main()
