apiVersion: v1
kind: Service
metadata:
  labels:
    name: letsencrypt
  name: letsencrypt
spec:
  type: LoadBalancer
  loadBalancerIP: 35.197.98.21
  ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: ssh
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
  selector:
    app: letsencrypt

---

# Not sure to understand how this stuff works with Services and the gcp load balancer/VMs stuff :-(
# It's supposed to open port 80, but I can access 22 and 443 as well...
# The UI for this is a bit confusing as well...
# TODO: Understand and fix this.
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: letsencrypt-http
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "letsencrypt-public"
spec:
  backend:
    serviceName: letsencrypt
    servicePort: 80

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: letsencrypt
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: letsencrypt
    spec:
      containers:
      - name: nginx
        image: gcr.io/sw-jenkins-build-storage/letsencrypt:latest
        env:
          - name: DOMAINS
            value: >
              alertmanager.dev.corp.arista.io
              apiserver.dev.corp.arista.io
              geiger.dev.corp.arista.io
              grafana.dev.corp.arista.io
              ingest.dev.corp.arista.io
              kafkaui.dev.corp.arista.io
              prometheus.dev.corp.arista.io
              registry.dev.corp.arista.io
              alertmanager.staging.corp.arista.io
              apiserver.staging.corp.arista.io
              geiger.staging.corp.arista.io
              grafana.staging.corp.arista.io
              ingest.staging.corp.arista.io
              kafkaui.staging.corp.arista.io
              prometheus.staging.corp.arista.io
              registry.staging.corp.arista.io
              npm.corp.arista.io
              godoc.corp.arista.io
              gocover.corp.arista.io
              jenkins.corp.arista.io
              gerrit.corp.arista.io
        ports:
        - containerPort: 22
        - containerPort: 80
        - containerPort: 442
        volumeMounts:
        - mountPath: /etc/letsencrypt
          name: letsencrypt-data
          subPath: letsencrypt
        - mountPath: /etc/nginx/sites-enabled
          name: letsencrypt-data
          subPath: sites-enabled
      volumes:
      - name: letsencrypt-data
        gcePersistentDisk:
          pdName: letsencrypt-data
          fsType: ext4
