
---

- name: Create /mnt/disks directory
  become: True
  file:
    path: /mnt/disks
    state: directory

- name: Move /data1 to /mnt/disks/data1
  become: True
  command: mv /data1 /mnt/disks/ creates=/mnt/disks/data1

- name: Create /mnt/disks/data[2-8] directories
  become: True
  file:
    path: "/mnt/disks/{{ item }}"
    state: directory
  with_items:
    - data2
    - data3
    - data4
    - data5
    - data6
    - data7
    - data8

- name: Make /mnt/disks/data[2-8] directories immutable
  become: True
  shell: "mountpoint /mnt/disks/{{ item }} || chattr =i /mnt/disks/{{ item }}"
  with_items:
    - data2
    - data3
    - data4
    - data5
    - data6
    - data7
    - data8

- name: Create mnt-disks-data[2-8].mount services to mount drives at /mnt/disks/data[2-8]
  become: True
  copy:
    dest: "/etc/systemd/system/mnt-disks-{{ item }}.mount"
    content: |
      [Mount]
      What=LABEL={{ item }}
      Where=/mnt/disks/{{ item }}
      Type=ext4
      Options=nofail
      TimeoutSec=10
  with_items:
    - data2
    - data3
    - data4
    - data5
    - data6
    - data7
    - data8

- name: stop data[2-8].mount services
  become: True
  systemd:
    name: "{{ item }}.mount"
    state: stopped
    daemon_reload: yes
  with_items:
    - data2
    - data3
    - data4
    - data5
    - data6
    - data7
    - data8

- name: relabel drives from DISK[2-8] to data[2-8]
  become: True
  ignore_errors: True
  shell: "existing=$(blkid -L {{ item.1 }}) && e2label ${existing} data{{ item.0 | int + 2 }}"
  with_indexed_items:
    - DISK2
    - DISK3
    - DISK4
    - DISK5
    - DISK6
    - DISK7
    - DISK8

- name: start mnt-disks-data[2-8].mount services
  become: True
  ignore_errors: True
  systemd:
    name: "mnt-disks-{{ item }}.mount"
    state: started
  with_items:
    - data2
    - data3
    - data4
    - data5
    - data6
    - data7
    - data8
