# Change inotify parameters
# NOTE: These are also included in the ASB config step
# Value borrowed from Stest
# Relevant BUG(s): 42769, 89834
- name: "Set inotify max user instances"
  sysctl:
     name: fs.inotify.max_user_instances
     value: 32768
     state: present
     sysctl_file: "/etc/sysctl.d/build.conf"

# Value borrowed from Stest
# Relevant BUG(s): 136042
- name: "Set inotify max user watchers"
  sysctl:
     name: fs.inotify.max_user_watchers
     value: 524288
     state: present
     sysctl_file: "/etc/sysctl.d/build.conf"
     reload: yes
