---

- assert:
    that: since is defined
    msg: "var: 'since' has not been defined"

- name: "Get all node status"
  shell: nodetool status | egrep -e '^[A-Z][A-Z]' | awk '{print($1)}'
  register: status_info

- debug: var=status_info

- name: "Check that all nodes are in UN"
  assert:
    that: item == "UN"
    msg: "Not all nodes in UN status"
  with_items: "{{ status_info.stdout_lines | default([]) | list }}"

- name: "Check errors in Scylla server journal"
  shell: journalctl -u scylla-server -q -p err..warning --no-pager --since '{{ since }}'
  register: error_info
  ignore_errors: true

- name: "Count errors"
  set_fact: server_health_errors="{{ error_info.stdout_lines | default([]) | length }}"

- debug: msg="Errors detected. Review scylla-server logs."
  when: "{{ server_health_errors }} > 0"

- debug: var=error_info
  when: "{{ server_health_errors }} > 0"
...
