---
- name: "Install telegraf"
  yum:
     name: telegraf-Linux
     state: installed

- name: "Make sure vmstat is running"
  shell: "/sbin/chkconfig --add vmstat"
  ignore_errors: yes

- name: "Set maximum RAID sync speed"
  sysctl:
      name: dev.raid.speed_limit_max
      value: 100000
      state: present
      sysctl_set: yes
      reload: yes
      sysctl_file: /etc/sysctl.d/stest.conf

- name: "Set minimum RAID sync speed"
  sysctl:
      name: dev.raid.speed_limit_min
      value: 1000
      state: present
      sysctl_set: yes
      reload: yes
      sysctl_file: /etc/sysctl.d/stest.conf

- name: "Add stest server build tags"
  shell: "Abuildd --addtags=\"fedora18 medium largemem bs2xx\""

- name: "Install Stest package"
  yum:
      name: AroraConfig-stest
      state: installed

- name: "Add server to arventory"
  shell: arventory update

- name: "Setup serial console"
  shell: "/usr/sbin/SetupAroraSerial"

- name: "Update datacenter.servers with status configuration ready"
  command: "{{ASB_DB_UPDATE_CFGRDY}}"

- name: "Reboot"
  command: "reboot"
...
