
---

- name: Create hadoop data directory
  become: True
  file:
    path: "{{ item }}/dfs"
    state: directory
    owner: 1000
    group: 1000
    mode: 0755
  with_items:
    - /data1
    - /data2
    - /data3
    - /data4
    - /data5
    - /data6
    - /data7
    - /data8
  ignore_errors: True
