# Copyright (c) 2017 Arista Networks, Inc.  All rights reserved.
# Arista Networks, Inc. Confidential and Proprietary.
# Subject to Arista Networks, Inc.'s EULA.
# FOR INTERNAL USE ONLY. NOT FOR DISTRIBUTION.

- name: add nginx catchall configmap
  kubernetes:
    api_endpoint: 127.0.0.1:8001
    state: apply
    insecure: true
    inline_data: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: nginx-catchall-config
      data:
        nginx.conf: |
          # Copyright (c) 2015 Arista Networks, Inc.  All rights reserved.
          # Arista Networks, Inc. Confidential and Proprietary.
          user  nginx;
          worker_processes  1;

          error_log  stderr warn;
          pid        /var/run/nginx.pid;

          events {
              worker_connections  1024;
          }

          http {
              default_type  text/plain;

              log_format  main  '$remote_addr $host - $remote_user [$time_local] "$request" '
                                '$status $body_bytes_sent "$http_referer" '
                                '"$http_user_agent" "$http_x_forwarded_for"';

              access_log  stdout main;

              keepalive_timeout  65;

              server {
                  listen       8080;
                  server_name  localhost;
                  server_tokens off;

                  location / {
                      return 404 "404 Not Found";
                  }
              }
          }

- import_tasks: proxy_public.yml

- import_tasks: proxy_internal.yml
  when: cluster_name in ['dev', 'staging']
