# Copyright (c) 2017 Arista Networks, Inc.  All rights reserved.
# Arista Networks, Inc. Confidential and Proprietary.
# Subject to Arista Networks, Inc.'s EULA.
# FOR INTERNAL USE ONLY. NOT FOR DISTRIBUTION.

---

- name: deploy zookeeper cluster services
  kubernetes:
    api_endpoint: 127.0.0.1:8001
    insecure: true
    inline_data: |
      apiVersion: v1
      kind: Service
      metadata:
        name: zookeeper-{{ hostvars[item]['ZOOKEEPER_ID'] - 1 }}
      spec:
        clusterIP: None
        ports:
          - name: client
            port: 2181
          - name: followers
            port: 2888
          - name: election
            port: 3888
        selector:
          app: zookeeper
          server-id: "{{ hostvars[item]['ZOOKEEPER_ID'] - 1 }}"
  with_items: "{{ groups.zookeeper }}"

- name: deploy zookeeper cluster daemonsets
  kubernetes:
    api_endpoint: 127.0.0.1:8001
    insecure: true
    inline_data: |
      apiVersion: extensions/v1beta1
      kind: DaemonSet
      metadata:
        name: zookeeper-{{ hostvars[item]['ZOOKEEPER_ID'] - 1 }}
      spec:
        template:
          metadata:
            labels:
              app: zookeeper
              server-id: "{{ hostvars[item]['ZOOKEEPER_ID'] - 1 }}"
          spec:
            nodeSelector:
              zookeeper: "{{ hostvars[item]['ZOOKEEPER_ID'] - 1 }}"
            containers:
              - name: server
                image: registry.docker.sjc.aristanetworks.com:5000/aeris/k8s-zookeeper
                imagePullPolicy: Always
                ports:
                  - containerPort: 2181
                  - containerPort: 2888
                  - containerPort: 3888
                volumeMounts:
                  - mountPath: /zookeeper/data
                    name: data
                  - mountPath: /zookeeper/wal
                    name: wal
            volumes:
            - name: data
              hostPath:
                path: /data2/zookeeper/data
            - name: wal
              hostPath:
                path: /data3/zookeeper/wal
  with_items: "{{ groups.zookeeper }}"

- name: deploy zookeeper ui service
  kubernetes:
    api_endpoint: 127.0.0.1:8001
    insecure: true
    inline_data: |
      apiVersion: v1
      kind: Service
      metadata:
        name: zookeeperui
        labels:
          app: zookeeperui
        annotations:
          external_type: "http"
      spec:
        type: LoadBalancer
        ports:
        - port: 8080
        selector:
          app: zookeeperui

- name: deploy zookeeper ui rc
  kubernetes:
    api_endpoint: 127.0.0.1:8001
    insecure: true
    inline_data: |
      apiVersion: v1
      kind: ReplicationController
      metadata:
        name: zookeeperui
      spec:
        replicas: 1
        selector:
          app: zookeeperui
        template:
          metadata:
            name: zookeeperui
            labels:
              app: zookeeperui
          spec:
            containers:
              - name: zookeeperui
                image: vivint/zk-web-docker
                imagePullPolicy: Always
                env:
                  - name: DEFAULT_NODE
                    value: zookeeper-0:2181
                ports:
                  - containerPort: 8080

- name: deploy zookeeper prometheus exporter
  kubernetes:
    api_endpoint: 127.0.0.1:8001
    insecure: true
    inline_data: |
      apiVersion: v1
      kind: ReplicationController
      metadata:
        name: zk-prom
      spec:
        replicas: 1
        selector:
          app: zk-prom
        template:
          metadata:
            name: zk-prom
            labels:
              app: zk-prom
            annotations:
              prometheus.io/scrape: "true"
              prometheus.io/port: "9114"
          spec:
            containers:
            - name: prometheus
              image: registry.docker.sjc.aristanetworks.com:5000/k8s/zk-prom
              imagePullPolicy: Always
              args:
                - /usr/bin/zookeeper_exporter
                - zookeeper-0:2181
                - zookeeper-1:2181
                - zookeeper-2:2181
              ports:
                - containerPort: 9114
