---
- name: "Install Scylla server on node(s)"
  hosts: scylla_nodes
  become: yes
  become_user: root
  gather_facts: no
  serial: 50
  roles:
    - { role: server_setup_scyllaroot } 
    - { role: server_installer }
    - { role: server_configurator }
    - { role: server_starter }
...
