---

# Do a rolling (one node at a time) restart of the hosts
#
# inputs:
#   since = time in journalctl --since format
#
# example:
#   runner ./rolling_restart.yml li101,li102,li103 ./secret 'since="2017-07-24 10:00:00"'

- name: "Rolling restart of nodes"
  hosts: all
  become: yes
  become_user: root
  serial: 1
  roles:
    - { role: server_restarter }
...
