#!/usr/bin/env bash

# a wrapper around ansible-playbook to keep the command line simple

USAGE="Usage: $0 <playbook path> <inventory> [extra-vars]"

PLAYBOOK=${1?"plabook path missing. ${USAGE}"}
INVENTORY=${2?"inventory missing. ${USAGE}"}
EXTRA_VARS=${3-""}

OPTIONS="-c paramiko"

if [[ -z ${EXTRA_VARS} ]]; then
	ansible-playbook ${OPTIONS} -i ${INVENTORY} ${PLAYBOOK}
else
	ansible-playbook ${OPTIONS} -i ${INVENTORY} ${PLAYBOOK} -e "${EXTRA_VARS}"
fi
