# This role will install kubernetes on the specified hosts
# When this role is applied to a host group, it will
# look for some vars for each host and install the different k8s components based on those vars
# Here is the list of all the host variables that MUST be defined in order for this role
# to work correctly:
#   - K8S_MASTER - boolean - hostvar: Will flag this host as a k8s master server
#   - K8S_WORKER - boolean - hostvar: Will flag this host as a k8s worker server

---

- name: Create directories
  become: True
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0755
    state: directory
  with_items:
    - /opt/bin
    - /etc/kubernetes/ssl
    - /etc/kubernetes/manifests
    - /etc/flannel
    - /etc/systemd/system/flanneld.service.d
    - /etc/systemd/system/docker.service.d

- name: Install flannel config
  become: True
  copy:
    content: |
      FLANNELD_IFACE={{ ansible_host }}
      FLANNELD_ETCD_ENDPOINTS={% set comma = joiner(",") %}{% for host in groups.etcd2 %}{{ comma() }}http://{{ hostvars[host]['ansible_host'] }}:2379{% endfor %}
    dest: /etc/flannel/options.env
    owner: root
    group: root
    mode: 0600
  register: flannel_config

- name: Install flanneld service on k8s nodes
  become: True
  copy:
    src: roles/common/files/flanneld.service.40-ExecStartPre-symlink.conf
    dest: /etc/systemd/system/flanneld.service.d/40-ExecStartPre-symlink.conf
  register: flannel_service

- name: Install docker flanneld drop-in
  become: True
  copy:
    src: roles/common/files/docker.service.40-flannel.conf
    dest: /etc/systemd/system/docker.service.d/40-flannel.conf
  register: docker_flannel

- name: Reload systemd config
  become: True
  systemd:
    daemon_reload: yes
  when: docker_flannel.changed or flannel_config.changed or flannel_service.changed

- name: restart flannel service if needed
  become: True
  systemd:
    name: flanneld.service
    state: restarted
  when: flannel_config.changed or flannel_service.changed

# This is too dangerous and not really useful for now.
# Related github issues:
# https://github.com/moby/moby/issues/22789
# https://github.com/moby/moby/issues/21109
# Related trello card:
# https://trello.com/c/9fGfPtaZ
#
# - name: Restart docker daemon
#   become: True
#   command: systemctl restart docker.service
#   when: "K8S_MASTER == True or K8S_WORKER == True"
  # TODO: We should restart when we really changed something

- name: Get current k8s binary info
  become: True
  stat:
    path: /opt/bin/kubelet
  register: k8sbinary_file

- name: Check if k8s binary is correct
  become: True
  set_fact:
    force_new_download: "{{ k8sbinary_file.stat.exists == False or k8sbinary_file.stat.md5 != K8S_KUBELET_MD5 }}"

- name: Stop kubelet service
  become: True
  command: systemctl stop kubelet.service
  when: force_new_download
  # The service might not be installed yet, so we don't mind having errors
  ignore_errors: True

- name: Install k8s binary
  become: True
  get_url:
    url: http://dist/storage/Kubernetes/kubernetes-{{ K8S_VERSION }}-server-linux-amd64/server/bin/kubelet
    dest: /opt/bin/kubelet
    checksum: "md5:{{ K8S_KUBELET_MD5 }}"
    owner: root
    group: root
    mode: 0755
  when: force_new_download

- name: Install k8s certificates
  become: True
  copy:
    src: roles/k8s_vars/certs/{{ item }}
    dest: /etc/kubernetes/ssl/{{ item }}
    owner: root
    group: root
    mode: 0600
  with_items: "{{ certificates }}"

- name: Remove possible old-config manifest
  become: True
  file:
    path: /etc/kubernetes/manifests/kube-proxy.yaml
    state: absent

- name: Install k8s manifests
  become: True
  template:
    src: "{{ item }}.j2"
    dest: /etc/kubernetes/manifests/{{ item }}
    owner: root
    group: root
    mode: 0755
  with_items: "{{ manifests }}"

- name: Install kubeconfig.yaml
  become: True
  template:
    src: "{{ kubeconfig }}.yaml.j2"
    dest: "/etc/kubernetes/{{ kubeconfig }}.yaml"
    owner: root
    group: root
    mode: 0755

- name: Install k8s service
  become: True
  copy:
    # TODO: Make this a template
    content: |
      [Service]
      ExecStart=/opt/bin/kubelet \
        --require-kubeconfig=true \
        --kubeconfig=/etc/kubernetes/{{ kubeconfig }}.yaml \
      {% if K8S_MASTER %}
        --register-schedulable=false \
      {%else%}
        --register-node=true \
      {% endif %}
        --allow-privileged=true \
        --pod-manifest-path=/etc/kubernetes/manifests \
        --hostname-override={{ ansible_host }} \
        --cluster_dns=10.3.0.10 \
        --cluster_domain=cluster.local \
        --volume-stats-agg-period=0 \
        --cadvisor-port=4194{% if not K8S_MASTER %} \
        --tls-cert-file=/etc/kubernetes/ssl/worker.pem \
        --tls-private-key-file=/etc/kubernetes/ssl/worker-key.pem{% endif %}

      Restart=always
      RestartSec=10

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/kubelet.service
    owner: root
    group: root
    mode: 0644
  register: kservice

- name: Enable kubelet.service unit
  become: True
  systemd:
    name: kubelet.service
    enabled: yes

- name: Reload services
  become: True
  command: systemctl daemon-reload
  when: kservice.changed

- name: Restart k8s service if needed
  become: True
  command: systemctl restart kubelet.service
  when: "kservice.changed or force_new_download"
