
---

- name: Check if etcd certs already present
  stat:
    path: "{{ inventory_dir}}/files/etcd/client.pem"
  register: etcd_certs_done

- import_tasks: etcd_certs.yml
  when: not etcd_certs_done.stat.exists

- name: Check if k8s certs already present
  stat:
    path: "{{ inventory_dir}}/files/k8s/worker.pem"
  register: k8s_certs_done

- import_tasks: k8s_certs.yml
  when: not k8s_certs_done.stat.exists
