
---

- name: check if openvpn certs already present
  stat:
    path: "{{ inventory_dir}}/files/openvpn/dh2048.pem"
  register: openvpn_certs_done
  when: "'openvpn' in groups"

- import_tasks: openvpn_certs.yml
  when: "'openvpn' in groups and not openvpn_certs_done.stat.exists"

- name: check if etcd certs already present
  stat:
    path: "{{ inventory_dir}}/files/etcd/client.pem"
  register: etcd_certs_done

- import_tasks: etcd_certs.yml
  when: not etcd_certs_done.stat.exists

- name: check if k8s certs already present
  stat:
    path: "{{ inventory_dir}}/files/k8s/worker.pem"
  register: k8s_certs_done

- import_tasks: k8s_certs.yml
  when: not k8s_certs_done.stat.exists

- name: check if aeris certs already present
  stat:
    path: "{{ inventory_dir}}/files/aeris/ca.pem"
  register: aeris_certs_done

- import_tasks: aeris_certs.yml
  when: not aeris_certs_done.stat.exists
