---
# Start up all the services on Scylla node

- name: "Starting services"
  service: name={{ item }} state=started
  with_items:
    - collectd
    - node-exporter
    - scylla-server
    - telegraf

- assert:
    - that: "{{ BUG_SERIAL_STARTUP == 1 }}"
    - msg: "Change the startup procedure for parallel startup"

- name: "Wait for port 9042"
  wait_for: host="{{ ansible_hostname }}" port=9042 timeout="{{ PORT_UP_DELAY }}"

# JMX port is currently available only on localhost
- name: "Wait for port 7199"
  wait_for: port=7199 timeout="{{ PORT_UP_DELAY }}"

# Waiting for UN status from nodetool can be prone to issues
# like local host says UN while other nodes in the cluster think
# its DN. We believe UN/DN should be from cluster perspective and so
# such inconsistencies should only be temporal. There doesn't seem to
# be a better or more conclusive way of determining that local node
# has successfully started up. Under discussion with Scylla.
- name: "Wait for node to be UP and NORMAL as per nodetool"
  shell: nodetool status | grep {{ hostvars[ansible_host].ansible_default_ipv4.address }} | awk '{ print($1) }'
  register: nodetool_result
  until: nodetool_result.stdout == "UN"
  delay: "{{ NODETOOL_UN_DELAY }}"
  retries: "{{ NODETOOL_UN_RETRIES }}"
