---
# Start up all the services on Scylla node

- name: "Starting services"
  service: name={{ item }} state=started
  with_items:
          - collectd
          - node-exporter
          - scylla-server
          - telegraf
