- name: Install ssh keys
  copy:
    content: "{{ ssh_keys | join('\n') }}"
    dest: "/home/core/.ssh/authorized_keys.d/coreos-cloudinit"
    mode: 0600
  register: result

- name: Update ssh keys
  command: update-ssh-keys -l
  when: result.changed


- name: inotify config
  become: True
  copy:
    src: roles/common/files/inotify.conf
    dest: /etc/sysctl.d/inotify.conf
  register: result

- name: iconfig config reload
  become: True
  command: sysctl --system
  when: result.changed

- name: Install docker insecure registry
  # Note that docker daemon needs to be restarted in order for this change to
  # take effect, but as restarting docker daemon will stop all the
  # running docker containers, it's not done by ansible but left as a manual
  # process
  become: True
  copy:
    src: roles/common/files/docker.50-options.conf
    dest: /etc/systemd/system/docker.service.d/50-options.conf

# Arista is using two domains in the search.
# systemd-networkd is using only the first one from the dhcp server
# so we hardcode both in this config file to override the default config
# Bug: https://github.com/systemd/systemd/issues/2710
# FIXME: This might be fixed by https://github.com/systemd/systemd/pull/5932
# Validate and remove file if it works with this fix
- name: Fix search line in resolv.conf
  become: True
  copy:
    src: roles/common/files/zy-dhcp.network
    dest: /etc/systemd/network/zy-dhcp.network
  register: result

- name: Remove old dhcp.network file
  become: True
  file:
    path: /etc/systemd/network/20-dhcp.network
    state: absent

- name: Restart network to take dhcp search config into account
  become: True
  command: systemctl restart systemd-networkd
  when: result.changed
