- name: Install ssh keys
  copy:
    content: "{{ ssh_keys | join('\n') }}"
    dest: "/home/core/.ssh/authorized_keys.d/coreos-cloudinit"
    mode: 0600
  register: result

- name: Update ssh keys
  command: update-ssh-keys -l
  when: result.changed


- name: inotify config
  become: True
  copy:
    src: roles/common/files/inotify.conf
    dest: /etc/sysctl.d/inotify.conf
  register: result

- name: iconfig config reload
  become: True
  command: sysctl --system
  when: result.changed
