- name: Install ssh keys
  copy:
    content: "{{ ssh_keys | join('\n') }}"
    dest: "/home/core/.ssh/authorized_keys.d/coreos-cloudinit"
    mode: 0600
  register: result

- name: Update ssh keys
  command: update-ssh-keys -l
  when: result.changed


- name: inotify config
  become: True
  copy:
    src: roles/common/files/inotify.conf
    dest: /etc/sysctl.d/inotify.conf
  register: result

- name: disable ipv6
  become: True
  copy:
    src: roles/common/files/10-disable-ipv6.conf
    dest: /etc/sysctl.d/10-disable-ipv6.conf
  register: result2

- name: sysctl config reload
  become: True
  command: sysctl --system
  when: result.changed or result2.changed

- name: Install docker insecure registry
  # Note that docker daemon needs to be restarted in order for this change to
  # take effect, but as restarting docker daemon will stop all the
  # running docker containers, it's not done by ansible but left as a manual
  # process
  become: True
  copy:
    src: roles/common/files/docker.50-options.conf
    dest: /etc/systemd/system/docker.service.d/50-options.conf

# Workaround for bug:
# https://github.com/systemd/systemd/issues/3374#issuecomment-288882355
- name: Fix systemd-udevd bug
  become: True
  copy:
    src: roles/common/files/99-default.link
    dest: /etc/systemd/network/99-default.link
  register: result_99_default_link

# Arista is using two domains in the search.
# systemd-networkd is using only the first one from the dhcp server
# so we hardcode both in this config file to override the default config
# Bug: https://github.com/systemd/systemd/issues/2710
# FIXME: This might be fixed by https://github.com/systemd/systemd/pull/5932
# Validate and remove file if it works with this fix
- name: Fix search line in resolv.conf
  become: True
  copy:
    src: roles/common/files/zy-dhcp.network
    dest: /etc/systemd/network/zy-dhcp.network
  register: result_zy_dhcp_network

- name: Remove old 20-dhcp.network file
  become: True
  file:
    path: /etc/systemd/network/20-dhcp.network
    state: absent
  register: result_20_dhcp_network

- name: Remove old zzz-dhcp.network file
  become: True
  file:
    path: /etc/systemd/network/zzz-dhcp.network
    state: absent
  register: result_zzz_dhcp_network

- name: Remove old 99-dhcp.network file
  become: True
  file:
    path: /etc/systemd/network/99-dhcp.network
    state: absent
  register: result_99_dhcp_network

- name: Restart network to take dhcp search config into account
  become: True
  command: systemctl restart systemd-networkd
  when: >
      result_zy_dhcp_network.changed or result_20_dhcp_network.changed or
      result_zzz_dhcp_network.changed or result_99_dhcp_network.changed or
      result_99_default_link.changed

- name: Create the .bashrc.d folder so other roles can customize the core user shell
  file:
    path: "{{ ansible_env.HOME }}/.bashrc.d"
    mode: 0755
    state: directory

# Note: recommended method from the CoreOS team:
# https://github.com/coreos/bugs/issues/1342#issuecomment-241726123
- name: Install our bashrc so we can customize the core user shell
  copy:
    src: bashrc
    dest: "{{ ansible_env.HOME }}/.bashrc"
