---
- name: "Check network configuration is correct - /etc/sysconfig" 
  shell: ls -l /etc/sysconfig/network-scripts/ifcfg-* | grep -q {{ item }}
  with_items:
      - bond0
      - em1
      - em2
      - macvlan-bond0

- name: "Check network configuration is correct - MACADDR" 
  shell: grep MACADDR /etc/sysconfig/network-scripts/ifcfg-macvlan-bond0

- name: "Check network configuration is correct - ifconfig"
  shell: ifconfig {{ item }}
  with_items: 
      - bond0
      - em1
      - em2
      - macvlan-bond0

- name: "Make sure vmstat is running"
  shell: "/sbin/chkconfig --add vmstat"
   
- name: "Check that vmstat is running"
  shell: service vmstat status | grep "active"

- name: "Install MATE desktop environment"
  shell: echo "PREFERRED=mate-session" > /etc/sysconfig/desktop

- name: "Set up MATE desktop environment"
  shell: yum -y groupinstall "Mate Desktop"

- name: "Make sure no Abuilds are running"
  shell: Abuildd -s | grep "Abuildd is run never"

- name: "Check stest *isn't* installed - yum check"
  shell: "! yum list installed AroraConfig-stest"

- name: "Check stest *isn't* installed - rpm check"
  shell: "! rpm -q AroraConfig-stest"

- name: "Add server to arventory"
  shell: arventory update --markAsUserOnly

- name: "Verify server info is available via arventory"
  shell: arventory list -l {{ansible_hostname}} | grep -q "{{ansible_hostname}}" 

- name: "Delete cron job calling ASB"
  shell: "rm /etc/cron.d/ASB"

- name: "Send Thomas email"
  shell: "echo \"{{ASB_MAIL_BODY}}\" | mail -s {{ASB_MAIL_HEADER}} twieland@arista.com"

- name: "Update datacenter.servers with status for this machine as installed"
  command: >
      mysql -u arastra -e
      "UPDATE {{ASB_DB}} SET status=\"{{ASB_STATUS_INSTALLED}}\" WHERE\
       name=\"{{ansible_hostname}}\" AND domain=\"{{ASB_DEFAULT_DOMAIN}}\""
      -h mysql datacenter
...
