---
# Stop all the services on Scylla node

# Failures in drain would happen if
# Scylla service isn't running so ignore errors
# to make the stop idempotent
- name: "Drain Scylla server"
  shell: nodetool drain
  ignore_errors: true

# never stop telegraf and collected
- name: "Stopping services"
  service: name={{ item }} state=stopped
  with_items:
          - scylla-server
