---
- name: "Run common configuration steps"
  include: "{{STAGES_PATH}}/config_conf/config_common.yml"

- name: "Install MATE desktop environment"
  lineinfile:
      path: /etc/sysconfig/desktop
      line: "PREFERRED=mate-session"
      create: yes
      state: present

- name: "Set up MATE desktop environment"
  shell: yum -y groupinstall "Mate Desktop"

- name: "Make sure no Abuilds enabled"
  shell: "Abuildd -s | grep \"Abuildd is run never\""

- name: "Update datacenter.servers with status configuration ready"
  command: "{{ASB_DB_UPDATE_AUTH}}"

- name: "Reboot"
  command: "reboot"
...
