---
- name: "Run common configuration steps"
  include: "{{STAGES_PATH}}/config_conf/config_common.yml"

- name: "Enable abuilds"
  shell: "Abuildd --activate"

- name: "Update datacenter.servers with status configuration ready"
  command: "{{ASB_DB_UPDATE_AUTH}}"

- name: "Reboot"
  command: "reboot"
...
