---
- name: "Run common configuration steps"
  include: "{{STAGES_PATH}}/config_conf/config_common.yml"

- name: "Delete unnecessary server build tags"
  shell: "Abuildd --deltags=\"fedora14 bs3xx\""

- name: "Add stest server build tags"
  shell: "Abuildd --addtags=\"fedora18 medium largemem bs2xx\""

- name: "Install docker"
  yum:
      name: docker
      state: installed

- name: "Customize open file limit"
  become: True
  copy:
    src: 92-Stest.conf
    dest: /etc/security/limits.d/92-Stest.conf

- name: "Customize Max process limit"
  become: True
  copy:
    src: 92-Stest-nproc.conf
    dest: /etc/security/limits.d/93-Stest-nproc.conf

- name: "Customize inotify instances and watches"
  become: True
  copy:
    src: Stest.conf
    dest: /etc/sysctl.d/Stest.conf

- name: "Update sysctl"
  become: True
  command: sysctl --system

- name: "Add docker to rc.local"
  lineinfile:
     dest: /etc/rc.d/rc.local
     line: "systemctl start docker"

- name: "Install Stest package"
  yum:
      name: AroraConfig-stest
      state: installed

- name: "Enable Stests"
  shell: "{{STAGES_PATH}}/common_conf/changeCfg /etc/Arora.cfg Stest enabled True"

- name: "Update datacenter.servers with status configuration ready"
  command: "{{ASB_DB_UPDATE_AUTH}}"

- name: "Reboot"
  command: "reboot"
...
