---
- name: "Run common configuration steps"
  include: "{{STAGES_PATH}}/config_conf/config_common.yml"

- name: "Delete unnecessary server build tags"
  shell: "Abuildd --deltags=\"fedora14 bs3xx\""

- name: "Add stest server build tags"
  shell: "Abuildd --addtags=\"fedora18 medium largemem bs2xx\""

- name: "Install Stest package"
  yum:
      name: AroraConfig-stest
      state: installed

- name: "Enable Stests"
  shell: "{{STAGES_PATH}}/common_conf/changeCfg /etc/Arora.cfg Stest enabled True"

- name: "Update datacenter.servers with status configuration ready"
  command: "{{ASB_DB_UPDATE_AUTH}}"

- name: "Reboot"
  command: "reboot"
...
