---
- name: "Run common configuration steps"
  include: "{{STAGES_PATH}}/config_conf/config_common.yml"

- name: "Mark server as a user server on arventory"
  shell: "arventory update --markAsUserOnly"

- name: "Verify server is listed as user server via arventory"
  shell: "arventory freeUs | grep -q {{ ansible_hostname }}"

- name: "Install MATE desktop environment"
  lineinfile:
      dest: /etc/sysconfig/desktop
      line: "PREFERRED=mate-session"
      create: yes
      state: present

- name: "Set up MATE desktop environment"
  shell: yum -y groupinstall "Mate Desktop"

- name: "Make sure no Abuilds enabled"
  shell: "Abuildd -s | grep \"Abuildd is run never\""

- name: "Install docker"
  yum:
      name: docker
      state: installed

- name: "Add docker to rc.local"
  lineinfile:
     dest: /etc/rc.d/rc.local
     line: "systemctl start docker"

# ----------------------------------------------------------------------------------
# QFS Related Changes
# ----------------------------------------------------------------------------------

- name: "Mount /share as a bind mount - takes effect upon reboot"
  lineinfile:
     dest: /etc/fstab
     line: "/share /share none bind 0 0"

- name: "Mark /share as shared mount - takes effect upon reboot"
  lineinfile:
     dest: /etc/rc.d/rc.local
     line: "mount --make-shared /share"

# ----------------------------------------------------------------------------------

- name: "Update datacenter.servers with status configuration ready"
  command: "{{ASB_DB_UPDATE_AUTH}}"

- name: "Reboot"
  command: "reboot"
...
