---
- name: "Run common configuration steps"
  include: "{{STAGES_PATH}}/config_conf/config_common.yml"

- name: "Delete unnecessary server build tags"
  shell: "Abuildd --deltags=\"fedora14 bs2xx\""

- name: "Add build server build tags"
  shell: "Abuildd --addtags=\"fedora18 largemem bs3xx\""

- name: "Install Abuild-asyncDeleteTree - only relevant for build servers to clean up after builds"
  yum:
      name: Abuild-asyncDeleteTree
      state: present
  
# ------------------------
# Arjobd related changes
# ------------------------

- name: "Install Arjobd package containing the service file"
  yum:
     name: Arsched-Arjobd
     state: present

- name: "Start Arjobd service"
  service:
     name: Arjobd
     state: started

# ------------------------

- name: "Enable abuilds"
  shell: "Abuildd --activate"

- name: "Install QUBIT uploader"
  yum:
    name: qubit-abuild-upload
    state: present

- name: "Start QUBIT uploader"
  service:
    name: abuild-qupload
    state: started

- name: "Update datacenter.servers with status configuration ready"
  command: "{{ASB_DB_UPDATE_AUTH}}"

- name: "Reboot"
  command: "reboot"
...
