stest_conf:
   repair_start: default
   repair_running: default
   repair_verify: default
   reimage_healthcheck: stest
   reimage_wipe: default
   reimage_verify: default
   disk: default
   os: default
   resync_running: default
   config: stest
   auth: default
   cleanup: default
