---
#NOTE: Do not change this file unless you have a good reason.

- name: "Gather info about the disks."
  include: "gather_disk_info.yml"

# ------------------------------- SANITY CHECK ----------------------------------
- name: "Reimage: Sanity check"
  include: "reimage_sanity_default.yml"
  when: STATUS == ASB_STATUS_REIMG

# --------------------------------- DISK WIPE -----------------------------------
- name: "Reimage: Complete disk wipe"
  include: "reimage_wipe_default.yml"
  when: STATUS == ASB_STATUS_REIMG_SANITYRDY

# ---------------------------------- VERIFY -------------------------------------
- name: "Reimage: Verify wipe was successful"
  include: "reimage_verify_default.yml"
  when: STATUS == ASB_STATUS_REIMG_WIPERDY
...
