---
# ----------------------------------------------------------------------------------
# XXX: This is stupid workaround because block/rescue don't work in included files
# for Ansible 2.1    >:(
- name: "Wipe the disks and remove all partitions/RAID arrays"
  command: "{{role_path}}/files/reimage.py wipe"
  register: SANITY
  ignore_errors: true

- name: "Send SOS email about this machine"
  shell: "{{ASB_MAIL_REIMG_WIPE_ERR}}"
  when: SANITY | failed

- name: "There's nothing more than ASB can do..."
  command: "{{ASB_DB_UPDATE_DEAD}}"
  when: SANITY | failed

- fail: msg="Automatic wipe of this machine was unsuccessful."
  when: SANITY | failed
# ----------------------------------------------------------------------------------

- name: "Turn off firewall to enable booting from PXE server successful"
  command: "service iptables stop"

- name: "Verify pxe server is reachable"
  command: "ping -c 5 pxe"

- name: "Update server status"
  command: "{{ASB_DB_UPDATE_REIMG_WIPERDY}}"

- name: "Reboot with f18"
  shell: "pxe-kexec -n pxe <<< \"f18-arora-pxe-kexec\""
...
