---
- name: "Simple playbook to add, search, and edit a file -  /etc/motd" 
  hosts: all
  become: yes
  become_user: root
  tasks:
      - name: "Add a line to /etc/motd"
        lineinfile: 
            path: /etc/motd
            line: "THIS IS A TEST LINE FOR SCALEIT - WILL BE REMOVED SOON"
            state: present
            

      - name: "Change a line in /etc/motd"
        lineinfile:
            path: /etc/motd
            regexp: "SCALEIT"
            line: "scaleit"

      - name: "Remove a line from /etc/motd"
        lineinfile:
            path: /etc/motd
            regexp: "scaleit"
            state: absent
...
