# we need to wait for the following bug fix to use a newer version:
# https://github.com/ansible/ansible/issues/20508
- assert:
    that: ansible_version.major == 2 and ansible_version.minor < 2

- name: Init some generated vars from config
  set_fact:
    k8s_masters: []

- name: Generates list of k8s masters
  set_fact:
    k8s_masters: "{{ k8s_masters }} + [ '{{ hostvars[item]['ansible_host'] }}' ]"
  with_items: "{{ groups.coreos }}"
  when: hostvars[item]['K8S_MASTER']

# Validate config
- name: Validate number of k8s masters
  assert:
    that: k8s_masters|length == 1
    msg: "Only one kubernetes master is supported"
