apiVersion: v1
kind: ConfigMap
metadata:
  name: alerts
data:
  config.yml: |

    # Alert for any instance that is unreachable for more than 5 minutes.
    ALERT InstanceDown
    IF up == 0
    FOR 5m
    LABELS { severity = "critical" }
    ANNOTATIONS {
      summary = "Instance {{ $labels.instance }} down",
      description = "{{ $labels.app }} ({{ $labels.instance }}) has been down for more than 5 minutes.",
    }
