apiVersion: v1
kind: ConfigMap
metadata:
  name: alerts
data:
  config.yml: |

    groups:
    - name: alerts.rules
      rules:

      # Alert for any instance that is unreachable for >5 minutes.
      - alert: InstanceDown
        expr: up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Instance {{ $labels.instance }} down
          description: '{{ $labels.app }} ({{ $labels.instance }}) has been down for more than 5 minutes.'

      # Alert when a /dataX disk reaches >80% usage.
      - alert: DiskUsageHigh
        expr: 100.0-100*(label_replace(node_filesystem_avail{mountpoint=~"/rootfs/data.*"},'mountpoint','$1$3','mountpoint','(/)(rootfs)/?(.*)')/label_replace(node_filesystem_size{mountpoint=~"/rootfs/data.*"},'mountpoint','$1$3','mountpoint','(/)(rootfs)/?(.*)')) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: High disk usage on {{ $labels.instance }} for {{ $labels.mountpoint }}.
          description: 'Disk usage on node {{ $labels.instance }}) at {{ $labels.mountpoint }} is {{ $value }}%.'

      # Alert when a /dataX disk reaches >90% usage.
      - alert: DiskUsageVeryHigh
        expr: 100.0-100*(label_replace(node_filesystem_avail{mountpoint=~"/rootfs/data.*"},'mountpoint','$1$3','mountpoint','(/)(rootfs)/?(.*)')/label_replace(node_filesystem_size{mountpoint=~"/rootfs/data.*"},'mountpoint','$1$3','mountpoint','(/)(rootfs)/?(.*)')) > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: Very high disk usage on {{ $labels.instance }} for {{ $labels.mountpoint }}.
          description: 'Disk usage on node {{ $labels.instance }}) at {{ $labels.mountpoint }} is {{ $value }}%.'

      # Alert when a /dataX disk becomes read-only.
      - alert: DiskReadOnly
        expr: label_replace(node_filesystem_readonly{mountpoint=~"/rootfs/data.*"},'mountpoint','$1$3','mountpoint','(/)(rootfs)/?(.*)') == 1
        for: 1m
        labels:
          severity: info
        annotations:
          summary: Disk has become read-only.
          description: 'Disk on node {{ $labels.instance }}) at {{ $labels.mountpoint }} is now read-only.'
