// Copyright (c) 2025 Arista Networks, Inc.  All rights reserved.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the COPYING file.

// ------------------------------------------------------------------------------------------------
//
// The Arista Portal APIs provide CloudVision with programmatic access to resources
// available on the arista.com site.
//
// Resources include:
//      * AlertBase updates (AlertBase.json) and
//      * device software downloads.
//
// APIToken & APITokenConfig are the resource API models which facilitate users to set,
// delete and check the presence of a valid Arista Portal API token.
//
// On-premises deployments may require a proxy to allow reachability between CloudVision
// and arista.com depending on the deployment environment. APIProxy & APIProxyConfig are the
// resource API models which can be used to configure CloudVision with a proxy URL where relevant.
//
// ------------------------------------------------------------------------------------------------

//
// Code generated by boomtown. DO NOT EDIT.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.4
// source: arista/arista_portal.v1/services.gen.proto

package arista_portal

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	APIProxyService_GetOne_FullMethodName        = "/arista.arista_portal.v1.APIProxyService/GetOne"
	APIProxyService_GetAll_FullMethodName        = "/arista.arista_portal.v1.APIProxyService/GetAll"
	APIProxyService_Subscribe_FullMethodName     = "/arista.arista_portal.v1.APIProxyService/Subscribe"
	APIProxyService_SubscribeMeta_FullMethodName = "/arista.arista_portal.v1.APIProxyService/SubscribeMeta"
)

// APIProxyServiceClient is the client API for APIProxyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIProxyServiceClient interface {
	GetOne(ctx context.Context, in *APIProxyRequest, opts ...grpc.CallOption) (*APIProxyResponse, error)
	GetAll(ctx context.Context, in *APIProxyStreamRequest, opts ...grpc.CallOption) (APIProxyService_GetAllClient, error)
	Subscribe(ctx context.Context, in *APIProxyStreamRequest, opts ...grpc.CallOption) (APIProxyService_SubscribeClient, error)
	SubscribeMeta(ctx context.Context, in *APIProxyStreamRequest, opts ...grpc.CallOption) (APIProxyService_SubscribeMetaClient, error)
}

type aPIProxyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIProxyServiceClient(cc grpc.ClientConnInterface) APIProxyServiceClient {
	return &aPIProxyServiceClient{cc}
}

func (c *aPIProxyServiceClient) GetOne(ctx context.Context, in *APIProxyRequest, opts ...grpc.CallOption) (*APIProxyResponse, error) {
	out := new(APIProxyResponse)
	err := c.cc.Invoke(ctx, APIProxyService_GetOne_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIProxyServiceClient) GetAll(ctx context.Context, in *APIProxyStreamRequest, opts ...grpc.CallOption) (APIProxyService_GetAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &APIProxyService_ServiceDesc.Streams[0], APIProxyService_GetAll_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIProxyServiceGetAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type APIProxyService_GetAllClient interface {
	Recv() (*APIProxyStreamResponse, error)
	grpc.ClientStream
}

type aPIProxyServiceGetAllClient struct {
	grpc.ClientStream
}

func (x *aPIProxyServiceGetAllClient) Recv() (*APIProxyStreamResponse, error) {
	m := new(APIProxyStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIProxyServiceClient) Subscribe(ctx context.Context, in *APIProxyStreamRequest, opts ...grpc.CallOption) (APIProxyService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &APIProxyService_ServiceDesc.Streams[1], APIProxyService_Subscribe_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIProxyServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type APIProxyService_SubscribeClient interface {
	Recv() (*APIProxyStreamResponse, error)
	grpc.ClientStream
}

type aPIProxyServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *aPIProxyServiceSubscribeClient) Recv() (*APIProxyStreamResponse, error) {
	m := new(APIProxyStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIProxyServiceClient) SubscribeMeta(ctx context.Context, in *APIProxyStreamRequest, opts ...grpc.CallOption) (APIProxyService_SubscribeMetaClient, error) {
	stream, err := c.cc.NewStream(ctx, &APIProxyService_ServiceDesc.Streams[2], APIProxyService_SubscribeMeta_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIProxyServiceSubscribeMetaClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type APIProxyService_SubscribeMetaClient interface {
	Recv() (*MetaResponse, error)
	grpc.ClientStream
}

type aPIProxyServiceSubscribeMetaClient struct {
	grpc.ClientStream
}

func (x *aPIProxyServiceSubscribeMetaClient) Recv() (*MetaResponse, error) {
	m := new(MetaResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// APIProxyServiceServer is the server API for APIProxyService service.
// All implementations must embed UnimplementedAPIProxyServiceServer
// for forward compatibility
type APIProxyServiceServer interface {
	GetOne(context.Context, *APIProxyRequest) (*APIProxyResponse, error)
	GetAll(*APIProxyStreamRequest, APIProxyService_GetAllServer) error
	Subscribe(*APIProxyStreamRequest, APIProxyService_SubscribeServer) error
	SubscribeMeta(*APIProxyStreamRequest, APIProxyService_SubscribeMetaServer) error
	mustEmbedUnimplementedAPIProxyServiceServer()
}

// UnimplementedAPIProxyServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAPIProxyServiceServer struct {
}

func (UnimplementedAPIProxyServiceServer) GetOne(context.Context, *APIProxyRequest) (*APIProxyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (UnimplementedAPIProxyServiceServer) GetAll(*APIProxyStreamRequest, APIProxyService_GetAllServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedAPIProxyServiceServer) Subscribe(*APIProxyStreamRequest, APIProxyService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedAPIProxyServiceServer) SubscribeMeta(*APIProxyStreamRequest, APIProxyService_SubscribeMetaServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeMeta not implemented")
}
func (UnimplementedAPIProxyServiceServer) mustEmbedUnimplementedAPIProxyServiceServer() {}

// UnsafeAPIProxyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIProxyServiceServer will
// result in compilation errors.
type UnsafeAPIProxyServiceServer interface {
	mustEmbedUnimplementedAPIProxyServiceServer()
}

func RegisterAPIProxyServiceServer(s grpc.ServiceRegistrar, srv APIProxyServiceServer) {
	s.RegisterService(&APIProxyService_ServiceDesc, srv)
}

func _APIProxyService_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIProxyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIProxyServiceServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIProxyService_GetOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIProxyServiceServer).GetOne(ctx, req.(*APIProxyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIProxyService_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(APIProxyStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIProxyServiceServer).GetAll(m, &aPIProxyServiceGetAllServer{stream})
}

type APIProxyService_GetAllServer interface {
	Send(*APIProxyStreamResponse) error
	grpc.ServerStream
}

type aPIProxyServiceGetAllServer struct {
	grpc.ServerStream
}

func (x *aPIProxyServiceGetAllServer) Send(m *APIProxyStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _APIProxyService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(APIProxyStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIProxyServiceServer).Subscribe(m, &aPIProxyServiceSubscribeServer{stream})
}

type APIProxyService_SubscribeServer interface {
	Send(*APIProxyStreamResponse) error
	grpc.ServerStream
}

type aPIProxyServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *aPIProxyServiceSubscribeServer) Send(m *APIProxyStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _APIProxyService_SubscribeMeta_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(APIProxyStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIProxyServiceServer).SubscribeMeta(m, &aPIProxyServiceSubscribeMetaServer{stream})
}

type APIProxyService_SubscribeMetaServer interface {
	Send(*MetaResponse) error
	grpc.ServerStream
}

type aPIProxyServiceSubscribeMetaServer struct {
	grpc.ServerStream
}

func (x *aPIProxyServiceSubscribeMetaServer) Send(m *MetaResponse) error {
	return x.ServerStream.SendMsg(m)
}

// APIProxyService_ServiceDesc is the grpc.ServiceDesc for APIProxyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var APIProxyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arista.arista_portal.v1.APIProxyService",
	HandlerType: (*APIProxyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOne",
			Handler:    _APIProxyService_GetOne_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAll",
			Handler:       _APIProxyService_GetAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _APIProxyService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeMeta",
			Handler:       _APIProxyService_SubscribeMeta_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "arista/arista_portal.v1/services.gen.proto",
}

const (
	APIProxyConfigService_GetOne_FullMethodName        = "/arista.arista_portal.v1.APIProxyConfigService/GetOne"
	APIProxyConfigService_GetAll_FullMethodName        = "/arista.arista_portal.v1.APIProxyConfigService/GetAll"
	APIProxyConfigService_Subscribe_FullMethodName     = "/arista.arista_portal.v1.APIProxyConfigService/Subscribe"
	APIProxyConfigService_SubscribeMeta_FullMethodName = "/arista.arista_portal.v1.APIProxyConfigService/SubscribeMeta"
	APIProxyConfigService_Set_FullMethodName           = "/arista.arista_portal.v1.APIProxyConfigService/Set"
	APIProxyConfigService_Delete_FullMethodName        = "/arista.arista_portal.v1.APIProxyConfigService/Delete"
)

// APIProxyConfigServiceClient is the client API for APIProxyConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APIProxyConfigServiceClient interface {
	GetOne(ctx context.Context, in *APIProxyConfigRequest, opts ...grpc.CallOption) (*APIProxyConfigResponse, error)
	GetAll(ctx context.Context, in *APIProxyConfigStreamRequest, opts ...grpc.CallOption) (APIProxyConfigService_GetAllClient, error)
	Subscribe(ctx context.Context, in *APIProxyConfigStreamRequest, opts ...grpc.CallOption) (APIProxyConfigService_SubscribeClient, error)
	SubscribeMeta(ctx context.Context, in *APIProxyConfigStreamRequest, opts ...grpc.CallOption) (APIProxyConfigService_SubscribeMetaClient, error)
	Set(ctx context.Context, in *APIProxyConfigSetRequest, opts ...grpc.CallOption) (*APIProxyConfigSetResponse, error)
	Delete(ctx context.Context, in *APIProxyConfigDeleteRequest, opts ...grpc.CallOption) (*APIProxyConfigDeleteResponse, error)
}

type aPIProxyConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAPIProxyConfigServiceClient(cc grpc.ClientConnInterface) APIProxyConfigServiceClient {
	return &aPIProxyConfigServiceClient{cc}
}

func (c *aPIProxyConfigServiceClient) GetOne(ctx context.Context, in *APIProxyConfigRequest, opts ...grpc.CallOption) (*APIProxyConfigResponse, error) {
	out := new(APIProxyConfigResponse)
	err := c.cc.Invoke(ctx, APIProxyConfigService_GetOne_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIProxyConfigServiceClient) GetAll(ctx context.Context, in *APIProxyConfigStreamRequest, opts ...grpc.CallOption) (APIProxyConfigService_GetAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &APIProxyConfigService_ServiceDesc.Streams[0], APIProxyConfigService_GetAll_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIProxyConfigServiceGetAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type APIProxyConfigService_GetAllClient interface {
	Recv() (*APIProxyConfigStreamResponse, error)
	grpc.ClientStream
}

type aPIProxyConfigServiceGetAllClient struct {
	grpc.ClientStream
}

func (x *aPIProxyConfigServiceGetAllClient) Recv() (*APIProxyConfigStreamResponse, error) {
	m := new(APIProxyConfigStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIProxyConfigServiceClient) Subscribe(ctx context.Context, in *APIProxyConfigStreamRequest, opts ...grpc.CallOption) (APIProxyConfigService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &APIProxyConfigService_ServiceDesc.Streams[1], APIProxyConfigService_Subscribe_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIProxyConfigServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type APIProxyConfigService_SubscribeClient interface {
	Recv() (*APIProxyConfigStreamResponse, error)
	grpc.ClientStream
}

type aPIProxyConfigServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *aPIProxyConfigServiceSubscribeClient) Recv() (*APIProxyConfigStreamResponse, error) {
	m := new(APIProxyConfigStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIProxyConfigServiceClient) SubscribeMeta(ctx context.Context, in *APIProxyConfigStreamRequest, opts ...grpc.CallOption) (APIProxyConfigService_SubscribeMetaClient, error) {
	stream, err := c.cc.NewStream(ctx, &APIProxyConfigService_ServiceDesc.Streams[2], APIProxyConfigService_SubscribeMeta_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aPIProxyConfigServiceSubscribeMetaClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type APIProxyConfigService_SubscribeMetaClient interface {
	Recv() (*MetaResponse, error)
	grpc.ClientStream
}

type aPIProxyConfigServiceSubscribeMetaClient struct {
	grpc.ClientStream
}

func (x *aPIProxyConfigServiceSubscribeMetaClient) Recv() (*MetaResponse, error) {
	m := new(MetaResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPIProxyConfigServiceClient) Set(ctx context.Context, in *APIProxyConfigSetRequest, opts ...grpc.CallOption) (*APIProxyConfigSetResponse, error) {
	out := new(APIProxyConfigSetResponse)
	err := c.cc.Invoke(ctx, APIProxyConfigService_Set_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPIProxyConfigServiceClient) Delete(ctx context.Context, in *APIProxyConfigDeleteRequest, opts ...grpc.CallOption) (*APIProxyConfigDeleteResponse, error) {
	out := new(APIProxyConfigDeleteResponse)
	err := c.cc.Invoke(ctx, APIProxyConfigService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APIProxyConfigServiceServer is the server API for APIProxyConfigService service.
// All implementations must embed UnimplementedAPIProxyConfigServiceServer
// for forward compatibility
type APIProxyConfigServiceServer interface {
	GetOne(context.Context, *APIProxyConfigRequest) (*APIProxyConfigResponse, error)
	GetAll(*APIProxyConfigStreamRequest, APIProxyConfigService_GetAllServer) error
	Subscribe(*APIProxyConfigStreamRequest, APIProxyConfigService_SubscribeServer) error
	SubscribeMeta(*APIProxyConfigStreamRequest, APIProxyConfigService_SubscribeMetaServer) error
	Set(context.Context, *APIProxyConfigSetRequest) (*APIProxyConfigSetResponse, error)
	Delete(context.Context, *APIProxyConfigDeleteRequest) (*APIProxyConfigDeleteResponse, error)
	mustEmbedUnimplementedAPIProxyConfigServiceServer()
}

// UnimplementedAPIProxyConfigServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAPIProxyConfigServiceServer struct {
}

func (UnimplementedAPIProxyConfigServiceServer) GetOne(context.Context, *APIProxyConfigRequest) (*APIProxyConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (UnimplementedAPIProxyConfigServiceServer) GetAll(*APIProxyConfigStreamRequest, APIProxyConfigService_GetAllServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedAPIProxyConfigServiceServer) Subscribe(*APIProxyConfigStreamRequest, APIProxyConfigService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedAPIProxyConfigServiceServer) SubscribeMeta(*APIProxyConfigStreamRequest, APIProxyConfigService_SubscribeMetaServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeMeta not implemented")
}
func (UnimplementedAPIProxyConfigServiceServer) Set(context.Context, *APIProxyConfigSetRequest) (*APIProxyConfigSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedAPIProxyConfigServiceServer) Delete(context.Context, *APIProxyConfigDeleteRequest) (*APIProxyConfigDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAPIProxyConfigServiceServer) mustEmbedUnimplementedAPIProxyConfigServiceServer() {}

// UnsafeAPIProxyConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APIProxyConfigServiceServer will
// result in compilation errors.
type UnsafeAPIProxyConfigServiceServer interface {
	mustEmbedUnimplementedAPIProxyConfigServiceServer()
}

func RegisterAPIProxyConfigServiceServer(s grpc.ServiceRegistrar, srv APIProxyConfigServiceServer) {
	s.RegisterService(&APIProxyConfigService_ServiceDesc, srv)
}

func _APIProxyConfigService_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIProxyConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIProxyConfigServiceServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIProxyConfigService_GetOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIProxyConfigServiceServer).GetOne(ctx, req.(*APIProxyConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIProxyConfigService_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(APIProxyConfigStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIProxyConfigServiceServer).GetAll(m, &aPIProxyConfigServiceGetAllServer{stream})
}

type APIProxyConfigService_GetAllServer interface {
	Send(*APIProxyConfigStreamResponse) error
	grpc.ServerStream
}

type aPIProxyConfigServiceGetAllServer struct {
	grpc.ServerStream
}

func (x *aPIProxyConfigServiceGetAllServer) Send(m *APIProxyConfigStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _APIProxyConfigService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(APIProxyConfigStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIProxyConfigServiceServer).Subscribe(m, &aPIProxyConfigServiceSubscribeServer{stream})
}

type APIProxyConfigService_SubscribeServer interface {
	Send(*APIProxyConfigStreamResponse) error
	grpc.ServerStream
}

type aPIProxyConfigServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *aPIProxyConfigServiceSubscribeServer) Send(m *APIProxyConfigStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _APIProxyConfigService_SubscribeMeta_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(APIProxyConfigStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APIProxyConfigServiceServer).SubscribeMeta(m, &aPIProxyConfigServiceSubscribeMetaServer{stream})
}

type APIProxyConfigService_SubscribeMetaServer interface {
	Send(*MetaResponse) error
	grpc.ServerStream
}

type aPIProxyConfigServiceSubscribeMetaServer struct {
	grpc.ServerStream
}

func (x *aPIProxyConfigServiceSubscribeMetaServer) Send(m *MetaResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _APIProxyConfigService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIProxyConfigSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIProxyConfigServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIProxyConfigService_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIProxyConfigServiceServer).Set(ctx, req.(*APIProxyConfigSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APIProxyConfigService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APIProxyConfigDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APIProxyConfigServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APIProxyConfigService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APIProxyConfigServiceServer).Delete(ctx, req.(*APIProxyConfigDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// APIProxyConfigService_ServiceDesc is the grpc.ServiceDesc for APIProxyConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var APIProxyConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arista.arista_portal.v1.APIProxyConfigService",
	HandlerType: (*APIProxyConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOne",
			Handler:    _APIProxyConfigService_GetOne_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _APIProxyConfigService_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _APIProxyConfigService_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAll",
			Handler:       _APIProxyConfigService_GetAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _APIProxyConfigService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeMeta",
			Handler:       _APIProxyConfigService_SubscribeMeta_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "arista/arista_portal.v1/services.gen.proto",
}

const (
	APITokenService_GetOne_FullMethodName        = "/arista.arista_portal.v1.APITokenService/GetOne"
	APITokenService_GetAll_FullMethodName        = "/arista.arista_portal.v1.APITokenService/GetAll"
	APITokenService_Subscribe_FullMethodName     = "/arista.arista_portal.v1.APITokenService/Subscribe"
	APITokenService_SubscribeMeta_FullMethodName = "/arista.arista_portal.v1.APITokenService/SubscribeMeta"
)

// APITokenServiceClient is the client API for APITokenService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APITokenServiceClient interface {
	GetOne(ctx context.Context, in *APITokenRequest, opts ...grpc.CallOption) (*APITokenResponse, error)
	GetAll(ctx context.Context, in *APITokenStreamRequest, opts ...grpc.CallOption) (APITokenService_GetAllClient, error)
	Subscribe(ctx context.Context, in *APITokenStreamRequest, opts ...grpc.CallOption) (APITokenService_SubscribeClient, error)
	SubscribeMeta(ctx context.Context, in *APITokenStreamRequest, opts ...grpc.CallOption) (APITokenService_SubscribeMetaClient, error)
}

type aPITokenServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAPITokenServiceClient(cc grpc.ClientConnInterface) APITokenServiceClient {
	return &aPITokenServiceClient{cc}
}

func (c *aPITokenServiceClient) GetOne(ctx context.Context, in *APITokenRequest, opts ...grpc.CallOption) (*APITokenResponse, error) {
	out := new(APITokenResponse)
	err := c.cc.Invoke(ctx, APITokenService_GetOne_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPITokenServiceClient) GetAll(ctx context.Context, in *APITokenStreamRequest, opts ...grpc.CallOption) (APITokenService_GetAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &APITokenService_ServiceDesc.Streams[0], APITokenService_GetAll_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aPITokenServiceGetAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type APITokenService_GetAllClient interface {
	Recv() (*APITokenStreamResponse, error)
	grpc.ClientStream
}

type aPITokenServiceGetAllClient struct {
	grpc.ClientStream
}

func (x *aPITokenServiceGetAllClient) Recv() (*APITokenStreamResponse, error) {
	m := new(APITokenStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPITokenServiceClient) Subscribe(ctx context.Context, in *APITokenStreamRequest, opts ...grpc.CallOption) (APITokenService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &APITokenService_ServiceDesc.Streams[1], APITokenService_Subscribe_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aPITokenServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type APITokenService_SubscribeClient interface {
	Recv() (*APITokenStreamResponse, error)
	grpc.ClientStream
}

type aPITokenServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *aPITokenServiceSubscribeClient) Recv() (*APITokenStreamResponse, error) {
	m := new(APITokenStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPITokenServiceClient) SubscribeMeta(ctx context.Context, in *APITokenStreamRequest, opts ...grpc.CallOption) (APITokenService_SubscribeMetaClient, error) {
	stream, err := c.cc.NewStream(ctx, &APITokenService_ServiceDesc.Streams[2], APITokenService_SubscribeMeta_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aPITokenServiceSubscribeMetaClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type APITokenService_SubscribeMetaClient interface {
	Recv() (*MetaResponse, error)
	grpc.ClientStream
}

type aPITokenServiceSubscribeMetaClient struct {
	grpc.ClientStream
}

func (x *aPITokenServiceSubscribeMetaClient) Recv() (*MetaResponse, error) {
	m := new(MetaResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// APITokenServiceServer is the server API for APITokenService service.
// All implementations must embed UnimplementedAPITokenServiceServer
// for forward compatibility
type APITokenServiceServer interface {
	GetOne(context.Context, *APITokenRequest) (*APITokenResponse, error)
	GetAll(*APITokenStreamRequest, APITokenService_GetAllServer) error
	Subscribe(*APITokenStreamRequest, APITokenService_SubscribeServer) error
	SubscribeMeta(*APITokenStreamRequest, APITokenService_SubscribeMetaServer) error
	mustEmbedUnimplementedAPITokenServiceServer()
}

// UnimplementedAPITokenServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAPITokenServiceServer struct {
}

func (UnimplementedAPITokenServiceServer) GetOne(context.Context, *APITokenRequest) (*APITokenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (UnimplementedAPITokenServiceServer) GetAll(*APITokenStreamRequest, APITokenService_GetAllServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedAPITokenServiceServer) Subscribe(*APITokenStreamRequest, APITokenService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedAPITokenServiceServer) SubscribeMeta(*APITokenStreamRequest, APITokenService_SubscribeMetaServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeMeta not implemented")
}
func (UnimplementedAPITokenServiceServer) mustEmbedUnimplementedAPITokenServiceServer() {}

// UnsafeAPITokenServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APITokenServiceServer will
// result in compilation errors.
type UnsafeAPITokenServiceServer interface {
	mustEmbedUnimplementedAPITokenServiceServer()
}

func RegisterAPITokenServiceServer(s grpc.ServiceRegistrar, srv APITokenServiceServer) {
	s.RegisterService(&APITokenService_ServiceDesc, srv)
}

func _APITokenService_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APITokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APITokenServiceServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APITokenService_GetOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APITokenServiceServer).GetOne(ctx, req.(*APITokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APITokenService_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(APITokenStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APITokenServiceServer).GetAll(m, &aPITokenServiceGetAllServer{stream})
}

type APITokenService_GetAllServer interface {
	Send(*APITokenStreamResponse) error
	grpc.ServerStream
}

type aPITokenServiceGetAllServer struct {
	grpc.ServerStream
}

func (x *aPITokenServiceGetAllServer) Send(m *APITokenStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _APITokenService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(APITokenStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APITokenServiceServer).Subscribe(m, &aPITokenServiceSubscribeServer{stream})
}

type APITokenService_SubscribeServer interface {
	Send(*APITokenStreamResponse) error
	grpc.ServerStream
}

type aPITokenServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *aPITokenServiceSubscribeServer) Send(m *APITokenStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _APITokenService_SubscribeMeta_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(APITokenStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APITokenServiceServer).SubscribeMeta(m, &aPITokenServiceSubscribeMetaServer{stream})
}

type APITokenService_SubscribeMetaServer interface {
	Send(*MetaResponse) error
	grpc.ServerStream
}

type aPITokenServiceSubscribeMetaServer struct {
	grpc.ServerStream
}

func (x *aPITokenServiceSubscribeMetaServer) Send(m *MetaResponse) error {
	return x.ServerStream.SendMsg(m)
}

// APITokenService_ServiceDesc is the grpc.ServiceDesc for APITokenService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var APITokenService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arista.arista_portal.v1.APITokenService",
	HandlerType: (*APITokenServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOne",
			Handler:    _APITokenService_GetOne_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAll",
			Handler:       _APITokenService_GetAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _APITokenService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeMeta",
			Handler:       _APITokenService_SubscribeMeta_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "arista/arista_portal.v1/services.gen.proto",
}

const (
	APITokenConfigService_GetOne_FullMethodName        = "/arista.arista_portal.v1.APITokenConfigService/GetOne"
	APITokenConfigService_GetAll_FullMethodName        = "/arista.arista_portal.v1.APITokenConfigService/GetAll"
	APITokenConfigService_Subscribe_FullMethodName     = "/arista.arista_portal.v1.APITokenConfigService/Subscribe"
	APITokenConfigService_SubscribeMeta_FullMethodName = "/arista.arista_portal.v1.APITokenConfigService/SubscribeMeta"
	APITokenConfigService_Set_FullMethodName           = "/arista.arista_portal.v1.APITokenConfigService/Set"
	APITokenConfigService_Delete_FullMethodName        = "/arista.arista_portal.v1.APITokenConfigService/Delete"
)

// APITokenConfigServiceClient is the client API for APITokenConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type APITokenConfigServiceClient interface {
	GetOne(ctx context.Context, in *APITokenConfigRequest, opts ...grpc.CallOption) (*APITokenConfigResponse, error)
	GetAll(ctx context.Context, in *APITokenConfigStreamRequest, opts ...grpc.CallOption) (APITokenConfigService_GetAllClient, error)
	Subscribe(ctx context.Context, in *APITokenConfigStreamRequest, opts ...grpc.CallOption) (APITokenConfigService_SubscribeClient, error)
	SubscribeMeta(ctx context.Context, in *APITokenConfigStreamRequest, opts ...grpc.CallOption) (APITokenConfigService_SubscribeMetaClient, error)
	Set(ctx context.Context, in *APITokenConfigSetRequest, opts ...grpc.CallOption) (*APITokenConfigSetResponse, error)
	Delete(ctx context.Context, in *APITokenConfigDeleteRequest, opts ...grpc.CallOption) (*APITokenConfigDeleteResponse, error)
}

type aPITokenConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAPITokenConfigServiceClient(cc grpc.ClientConnInterface) APITokenConfigServiceClient {
	return &aPITokenConfigServiceClient{cc}
}

func (c *aPITokenConfigServiceClient) GetOne(ctx context.Context, in *APITokenConfigRequest, opts ...grpc.CallOption) (*APITokenConfigResponse, error) {
	out := new(APITokenConfigResponse)
	err := c.cc.Invoke(ctx, APITokenConfigService_GetOne_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPITokenConfigServiceClient) GetAll(ctx context.Context, in *APITokenConfigStreamRequest, opts ...grpc.CallOption) (APITokenConfigService_GetAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &APITokenConfigService_ServiceDesc.Streams[0], APITokenConfigService_GetAll_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aPITokenConfigServiceGetAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type APITokenConfigService_GetAllClient interface {
	Recv() (*APITokenConfigStreamResponse, error)
	grpc.ClientStream
}

type aPITokenConfigServiceGetAllClient struct {
	grpc.ClientStream
}

func (x *aPITokenConfigServiceGetAllClient) Recv() (*APITokenConfigStreamResponse, error) {
	m := new(APITokenConfigStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPITokenConfigServiceClient) Subscribe(ctx context.Context, in *APITokenConfigStreamRequest, opts ...grpc.CallOption) (APITokenConfigService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &APITokenConfigService_ServiceDesc.Streams[1], APITokenConfigService_Subscribe_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aPITokenConfigServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type APITokenConfigService_SubscribeClient interface {
	Recv() (*APITokenConfigStreamResponse, error)
	grpc.ClientStream
}

type aPITokenConfigServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *aPITokenConfigServiceSubscribeClient) Recv() (*APITokenConfigStreamResponse, error) {
	m := new(APITokenConfigStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPITokenConfigServiceClient) SubscribeMeta(ctx context.Context, in *APITokenConfigStreamRequest, opts ...grpc.CallOption) (APITokenConfigService_SubscribeMetaClient, error) {
	stream, err := c.cc.NewStream(ctx, &APITokenConfigService_ServiceDesc.Streams[2], APITokenConfigService_SubscribeMeta_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &aPITokenConfigServiceSubscribeMetaClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type APITokenConfigService_SubscribeMetaClient interface {
	Recv() (*MetaResponse, error)
	grpc.ClientStream
}

type aPITokenConfigServiceSubscribeMetaClient struct {
	grpc.ClientStream
}

func (x *aPITokenConfigServiceSubscribeMetaClient) Recv() (*MetaResponse, error) {
	m := new(MetaResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *aPITokenConfigServiceClient) Set(ctx context.Context, in *APITokenConfigSetRequest, opts ...grpc.CallOption) (*APITokenConfigSetResponse, error) {
	out := new(APITokenConfigSetResponse)
	err := c.cc.Invoke(ctx, APITokenConfigService_Set_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aPITokenConfigServiceClient) Delete(ctx context.Context, in *APITokenConfigDeleteRequest, opts ...grpc.CallOption) (*APITokenConfigDeleteResponse, error) {
	out := new(APITokenConfigDeleteResponse)
	err := c.cc.Invoke(ctx, APITokenConfigService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// APITokenConfigServiceServer is the server API for APITokenConfigService service.
// All implementations must embed UnimplementedAPITokenConfigServiceServer
// for forward compatibility
type APITokenConfigServiceServer interface {
	GetOne(context.Context, *APITokenConfigRequest) (*APITokenConfigResponse, error)
	GetAll(*APITokenConfigStreamRequest, APITokenConfigService_GetAllServer) error
	Subscribe(*APITokenConfigStreamRequest, APITokenConfigService_SubscribeServer) error
	SubscribeMeta(*APITokenConfigStreamRequest, APITokenConfigService_SubscribeMetaServer) error
	Set(context.Context, *APITokenConfigSetRequest) (*APITokenConfigSetResponse, error)
	Delete(context.Context, *APITokenConfigDeleteRequest) (*APITokenConfigDeleteResponse, error)
	mustEmbedUnimplementedAPITokenConfigServiceServer()
}

// UnimplementedAPITokenConfigServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAPITokenConfigServiceServer struct {
}

func (UnimplementedAPITokenConfigServiceServer) GetOne(context.Context, *APITokenConfigRequest) (*APITokenConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (UnimplementedAPITokenConfigServiceServer) GetAll(*APITokenConfigStreamRequest, APITokenConfigService_GetAllServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedAPITokenConfigServiceServer) Subscribe(*APITokenConfigStreamRequest, APITokenConfigService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedAPITokenConfigServiceServer) SubscribeMeta(*APITokenConfigStreamRequest, APITokenConfigService_SubscribeMetaServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeMeta not implemented")
}
func (UnimplementedAPITokenConfigServiceServer) Set(context.Context, *APITokenConfigSetRequest) (*APITokenConfigSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedAPITokenConfigServiceServer) Delete(context.Context, *APITokenConfigDeleteRequest) (*APITokenConfigDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedAPITokenConfigServiceServer) mustEmbedUnimplementedAPITokenConfigServiceServer() {}

// UnsafeAPITokenConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to APITokenConfigServiceServer will
// result in compilation errors.
type UnsafeAPITokenConfigServiceServer interface {
	mustEmbedUnimplementedAPITokenConfigServiceServer()
}

func RegisterAPITokenConfigServiceServer(s grpc.ServiceRegistrar, srv APITokenConfigServiceServer) {
	s.RegisterService(&APITokenConfigService_ServiceDesc, srv)
}

func _APITokenConfigService_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APITokenConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APITokenConfigServiceServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APITokenConfigService_GetOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APITokenConfigServiceServer).GetOne(ctx, req.(*APITokenConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APITokenConfigService_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(APITokenConfigStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APITokenConfigServiceServer).GetAll(m, &aPITokenConfigServiceGetAllServer{stream})
}

type APITokenConfigService_GetAllServer interface {
	Send(*APITokenConfigStreamResponse) error
	grpc.ServerStream
}

type aPITokenConfigServiceGetAllServer struct {
	grpc.ServerStream
}

func (x *aPITokenConfigServiceGetAllServer) Send(m *APITokenConfigStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _APITokenConfigService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(APITokenConfigStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APITokenConfigServiceServer).Subscribe(m, &aPITokenConfigServiceSubscribeServer{stream})
}

type APITokenConfigService_SubscribeServer interface {
	Send(*APITokenConfigStreamResponse) error
	grpc.ServerStream
}

type aPITokenConfigServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *aPITokenConfigServiceSubscribeServer) Send(m *APITokenConfigStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _APITokenConfigService_SubscribeMeta_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(APITokenConfigStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(APITokenConfigServiceServer).SubscribeMeta(m, &aPITokenConfigServiceSubscribeMetaServer{stream})
}

type APITokenConfigService_SubscribeMetaServer interface {
	Send(*MetaResponse) error
	grpc.ServerStream
}

type aPITokenConfigServiceSubscribeMetaServer struct {
	grpc.ServerStream
}

func (x *aPITokenConfigServiceSubscribeMetaServer) Send(m *MetaResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _APITokenConfigService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APITokenConfigSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APITokenConfigServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APITokenConfigService_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APITokenConfigServiceServer).Set(ctx, req.(*APITokenConfigSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _APITokenConfigService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(APITokenConfigDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(APITokenConfigServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: APITokenConfigService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(APITokenConfigServiceServer).Delete(ctx, req.(*APITokenConfigDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// APITokenConfigService_ServiceDesc is the grpc.ServiceDesc for APITokenConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var APITokenConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arista.arista_portal.v1.APITokenConfigService",
	HandlerType: (*APITokenConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOne",
			Handler:    _APITokenConfigService_GetOne_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _APITokenConfigService_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _APITokenConfigService_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAll",
			Handler:       _APITokenConfigService_GetAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _APITokenConfigService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeMeta",
			Handler:       _APITokenConfigService_SubscribeMeta_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "arista/arista_portal.v1/services.gen.proto",
}
