---

- hosts: all
  gather_facts: False
  tasks:
    - name: Validate ansible version
      assert:
        that: "ansible_version.full | version_compare('2.4', '>=')"
        msg: "ansible v2.4 or later is required. {{ansible_version}}"

- hosts: coreos
  gather_facts: False
  roles:
    - defunctzombie.coreos-bootstrap

- hosts: coreos
  roles:
    - motd
    - coreos-config
    - data_folders
    - etc_hosts

- hosts: cvpbs
  roles:
    - cvpbs

- hosts: etcd2
  roles:
    - etcd2

- hosts: k8s_masters:k8s_workers
  roles:
    - k8s_cluster

- hosts: hadoop
  roles:
    - hadoop

- hosts: datanodes
  roles:
    - hadoop_datanode

- hosts: journalnodes
  roles:
    - hadoop_journalnode

- hosts: namenodes
  roles:
    - hadoop_namenode

- hosts: hbase
  roles:
    - hbase

- hosts: prometheus
  roles:
    - prometheus

- hosts: alertmanager
  roles:
    - alertmanager

- hosts: zookeeper
  roles:
    - zookeeper

- hosts: kafka_brokers
  roles:
    - kafka

- hosts: letsencrypt
  roles:
    - letsencrypt

- hosts: openvpn
  roles:
    - openvpn

- hosts: localhost
  roles:
    - k8s_services
