---
- include: bootstrap.yml

- hosts: coreos
  roles:
    - motd
    - coreos-config
    - data_folders

- hosts: k8s_cluster
  roles:
    - k8s_cluster

- hosts: hadoop
  roles:
    - hadoop

- hosts: local
  roles:
    - cloud-config
