---
- include: bootstrap.yml

- hosts: coreos
  roles:
    - motd
    - coreos-config
    - data_folders

- hosts: etcd2
  roles:
    - etcd2

- hosts: k8s_masters:k8s_workers
  roles:
    - k8s_cluster

- hosts: hadoop
  roles:
    - hadoop

- hosts: datanodes
  roles:
    - hadoop_datanode

- hosts: journalnodes
  roles:
    - hadoop_journalnode

- hosts: namenodes
  roles:
    - hadoop_namenode

- hosts: zookeeper
  roles:
    - zookeeper

- hosts: local
  roles:
    - cloud-config
