# Copyright (c) 2016 Arista Networks, Inc.  All rights reserved.
# Arista Networks, Inc. Confidential and Proprietary.

---
- name: "Manage Ansible configurations on hosts"
  hosts: all
  become: yes
  become_user: root
  vars:
    configf_path: '/etc/ansible/ansible.cfg'
  tasks:
    - name: "Replace with expected ansible configuration file for consistency"
      copy:
         src: ansible.cfg
         dest: "{{ configf_path }}"
         force: yes
...
