# Copyright (c) 2016 Arista Networks, Inc.  All rights reserved.
# Arista Networks, Inc. Confidential and Proprietary.

---
- name: "configs"
  hosts: all
  become: yes
  become_user: root
  vars:
    configs_ansibleCfgPath: '/etc/ansible/ansible.cfg'
  tasks:
    - name: "Replace with expected ansible configuration file for consistency"
      copy:
         src: ansible.cfg
         dest: "{{ configs_ansibleCfgPath }}"
         force: yes

    - name: "TEST"
      script: test/test_configs.sh
      when: TEST is defined
...
