# Copyright (c) 2016 Arista Networks, Inc.  All rights reserved.
# Arista Networks, Inc. Confidential and Proprietary.

# CONVERTED FROM ARORACONFIG
# Configuration for /etc/rc.d/rc.local
# Group: System Environment/Base
---
- name: "Update /rc.d/rclocal file"
  hosts: all
  become: yes
  become_user: root
  vars:
     rclocal_aroraConfigRclocal: "/var/lib/AroraConfig/rclocal"
     rclocal_sysconfdir: "/etc"
     rclocal_RCLOCAL: "{{rclocal_sysconfdir}}/rc.d/rc.local" 

  tasks:
     - stat: path="{{rclocal_aroraConfigRclocal}}"
       register: fixRclocal

     - block:
        - name: "Prepend missing shebang. Create rc.local if it doesn't exist."
          lineinfile:
             dest: "{{ rclocal_RCLOCAL }}"
             line: "#!/bin/sh"
             create: yes
             insertbefore: BOF
             state: present

        - name: "Change execution permissions for rc.local" 
          file:
             path: "{{ rclocal_RCLOCAL }}"
             mode: "a+x"

        - name: "Remove code that invokes sysctl-Arora.conf"
          lineinfile:
            dest: "{{ rclocal_RCLOCAL }}"
            regexp: "/etc/sysctl-Arora.conf"
            state: absent

        - name: "Remove code that invokes sysctl.d/Arora.conf in case there is a dup"
          lineinfile:
            dest: "{{ rclocal_RCLOCAL }}"
            regexp: "/etc/sysctl.d/Arora.conf"
            state: absent

        - name: "Append code to read in etc/sysctl.d/Arora.conf"
          lineinfile:
            dest: "{{ rclocal_RCLOCAL }}"
            line: "/sbin/sysctl -e -p /etc/sysctl.d/Arora.conf > /dev/null"
       when: fixRclocal.stat.exists == True
...        

