# Copyright (c) 2016 Arista Networks, Inc.  All rights reserved.
# Arista Networks, Inc. Confidential and Proprietary.

---
- name: "Update /etc/motd file with Ansible banner message"
  hosts: all
  become: yes
  become_user: root
  vars:
     updateMotd_motdPath: '/etc/motd'
     updateMotd_ansibleCfgMsg: "[ANSIBLE] {{ansible_date_time.date}} {{ansible_date_time.time}} : This machine \"{{ansible_hostname}}\" is managed by Ansible."
     updateMotd_exprToMatch: "^\\[ANSIBLE\\]"
  tasks:
     - name: "Remove duplicate /etc/motd messages"
       lineinfile: 
          dest: "{{ updateMotd_motdPath }}"
          regexp: "{{ updateMotd_exprToMatch }}"
          state: absent

     - name: "Add /etc/motd message"
       lineinfile: 
          dest: "{{ updateMotd_motdPath }}"
          insertbefore: BOF
          line: "{{ updateMotd_ansibleCfgMsg }}"
          create: yes
...
