// Copyright (c) 2023 Arista Networks, Inc.  All rights reserved.
// Use of this source code is governed by the Apache License 2.0
// that can be found in the COPYING file.

//
// Code generated by boomtown. DO NOT EDIT.
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v6.31.1
// source: arista/logging.v1/services.gen.proto

package logging

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	LoggingService_GetOne_FullMethodName        = "/arista.logging.v1.LoggingService/GetOne"
	LoggingService_GetSome_FullMethodName       = "/arista.logging.v1.LoggingService/GetSome"
	LoggingService_GetAll_FullMethodName        = "/arista.logging.v1.LoggingService/GetAll"
	LoggingService_Subscribe_FullMethodName     = "/arista.logging.v1.LoggingService/Subscribe"
	LoggingService_GetMeta_FullMethodName       = "/arista.logging.v1.LoggingService/GetMeta"
	LoggingService_SubscribeMeta_FullMethodName = "/arista.logging.v1.LoggingService/SubscribeMeta"
)

// LoggingServiceClient is the client API for LoggingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoggingServiceClient interface {
	GetOne(ctx context.Context, in *LoggingRequest, opts ...grpc.CallOption) (*LoggingResponse, error)
	GetSome(ctx context.Context, in *LoggingSomeRequest, opts ...grpc.CallOption) (LoggingService_GetSomeClient, error)
	GetAll(ctx context.Context, in *LoggingStreamRequest, opts ...grpc.CallOption) (LoggingService_GetAllClient, error)
	Subscribe(ctx context.Context, in *LoggingStreamRequest, opts ...grpc.CallOption) (LoggingService_SubscribeClient, error)
	GetMeta(ctx context.Context, in *LoggingStreamRequest, opts ...grpc.CallOption) (*MetaResponse, error)
	SubscribeMeta(ctx context.Context, in *LoggingStreamRequest, opts ...grpc.CallOption) (LoggingService_SubscribeMetaClient, error)
}

type loggingServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoggingServiceClient(cc grpc.ClientConnInterface) LoggingServiceClient {
	return &loggingServiceClient{cc}
}

func (c *loggingServiceClient) GetOne(ctx context.Context, in *LoggingRequest, opts ...grpc.CallOption) (*LoggingResponse, error) {
	out := new(LoggingResponse)
	err := c.cc.Invoke(ctx, LoggingService_GetOne_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggingServiceClient) GetSome(ctx context.Context, in *LoggingSomeRequest, opts ...grpc.CallOption) (LoggingService_GetSomeClient, error) {
	stream, err := c.cc.NewStream(ctx, &LoggingService_ServiceDesc.Streams[0], LoggingService_GetSome_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &loggingServiceGetSomeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LoggingService_GetSomeClient interface {
	Recv() (*LoggingSomeResponse, error)
	grpc.ClientStream
}

type loggingServiceGetSomeClient struct {
	grpc.ClientStream
}

func (x *loggingServiceGetSomeClient) Recv() (*LoggingSomeResponse, error) {
	m := new(LoggingSomeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *loggingServiceClient) GetAll(ctx context.Context, in *LoggingStreamRequest, opts ...grpc.CallOption) (LoggingService_GetAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &LoggingService_ServiceDesc.Streams[1], LoggingService_GetAll_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &loggingServiceGetAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LoggingService_GetAllClient interface {
	Recv() (*LoggingStreamResponse, error)
	grpc.ClientStream
}

type loggingServiceGetAllClient struct {
	grpc.ClientStream
}

func (x *loggingServiceGetAllClient) Recv() (*LoggingStreamResponse, error) {
	m := new(LoggingStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *loggingServiceClient) Subscribe(ctx context.Context, in *LoggingStreamRequest, opts ...grpc.CallOption) (LoggingService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &LoggingService_ServiceDesc.Streams[2], LoggingService_Subscribe_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &loggingServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LoggingService_SubscribeClient interface {
	Recv() (*LoggingStreamResponse, error)
	grpc.ClientStream
}

type loggingServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *loggingServiceSubscribeClient) Recv() (*LoggingStreamResponse, error) {
	m := new(LoggingStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *loggingServiceClient) GetMeta(ctx context.Context, in *LoggingStreamRequest, opts ...grpc.CallOption) (*MetaResponse, error) {
	out := new(MetaResponse)
	err := c.cc.Invoke(ctx, LoggingService_GetMeta_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggingServiceClient) SubscribeMeta(ctx context.Context, in *LoggingStreamRequest, opts ...grpc.CallOption) (LoggingService_SubscribeMetaClient, error) {
	stream, err := c.cc.NewStream(ctx, &LoggingService_ServiceDesc.Streams[3], LoggingService_SubscribeMeta_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &loggingServiceSubscribeMetaClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LoggingService_SubscribeMetaClient interface {
	Recv() (*MetaResponse, error)
	grpc.ClientStream
}

type loggingServiceSubscribeMetaClient struct {
	grpc.ClientStream
}

func (x *loggingServiceSubscribeMetaClient) Recv() (*MetaResponse, error) {
	m := new(MetaResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LoggingServiceServer is the server API for LoggingService service.
// All implementations must embed UnimplementedLoggingServiceServer
// for forward compatibility
type LoggingServiceServer interface {
	GetOne(context.Context, *LoggingRequest) (*LoggingResponse, error)
	GetSome(*LoggingSomeRequest, LoggingService_GetSomeServer) error
	GetAll(*LoggingStreamRequest, LoggingService_GetAllServer) error
	Subscribe(*LoggingStreamRequest, LoggingService_SubscribeServer) error
	GetMeta(context.Context, *LoggingStreamRequest) (*MetaResponse, error)
	SubscribeMeta(*LoggingStreamRequest, LoggingService_SubscribeMetaServer) error
	mustEmbedUnimplementedLoggingServiceServer()
}

// UnimplementedLoggingServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLoggingServiceServer struct {
}

func (UnimplementedLoggingServiceServer) GetOne(context.Context, *LoggingRequest) (*LoggingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (UnimplementedLoggingServiceServer) GetSome(*LoggingSomeRequest, LoggingService_GetSomeServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSome not implemented")
}
func (UnimplementedLoggingServiceServer) GetAll(*LoggingStreamRequest, LoggingService_GetAllServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedLoggingServiceServer) Subscribe(*LoggingStreamRequest, LoggingService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedLoggingServiceServer) GetMeta(context.Context, *LoggingStreamRequest) (*MetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMeta not implemented")
}
func (UnimplementedLoggingServiceServer) SubscribeMeta(*LoggingStreamRequest, LoggingService_SubscribeMetaServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeMeta not implemented")
}
func (UnimplementedLoggingServiceServer) mustEmbedUnimplementedLoggingServiceServer() {}

// UnsafeLoggingServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoggingServiceServer will
// result in compilation errors.
type UnsafeLoggingServiceServer interface {
	mustEmbedUnimplementedLoggingServiceServer()
}

func RegisterLoggingServiceServer(s grpc.ServiceRegistrar, srv LoggingServiceServer) {
	s.RegisterService(&LoggingService_ServiceDesc, srv)
}

func _LoggingService_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoggingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggingServiceServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoggingService_GetOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggingServiceServer).GetOne(ctx, req.(*LoggingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoggingService_GetSome_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoggingSomeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoggingServiceServer).GetSome(m, &loggingServiceGetSomeServer{stream})
}

type LoggingService_GetSomeServer interface {
	Send(*LoggingSomeResponse) error
	grpc.ServerStream
}

type loggingServiceGetSomeServer struct {
	grpc.ServerStream
}

func (x *loggingServiceGetSomeServer) Send(m *LoggingSomeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LoggingService_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoggingStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoggingServiceServer).GetAll(m, &loggingServiceGetAllServer{stream})
}

type LoggingService_GetAllServer interface {
	Send(*LoggingStreamResponse) error
	grpc.ServerStream
}

type loggingServiceGetAllServer struct {
	grpc.ServerStream
}

func (x *loggingServiceGetAllServer) Send(m *LoggingStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LoggingService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoggingStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoggingServiceServer).Subscribe(m, &loggingServiceSubscribeServer{stream})
}

type LoggingService_SubscribeServer interface {
	Send(*LoggingStreamResponse) error
	grpc.ServerStream
}

type loggingServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *loggingServiceSubscribeServer) Send(m *LoggingStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LoggingService_GetMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoggingStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggingServiceServer).GetMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoggingService_GetMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggingServiceServer).GetMeta(ctx, req.(*LoggingStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoggingService_SubscribeMeta_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoggingStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoggingServiceServer).SubscribeMeta(m, &loggingServiceSubscribeMetaServer{stream})
}

type LoggingService_SubscribeMetaServer interface {
	Send(*MetaResponse) error
	grpc.ServerStream
}

type loggingServiceSubscribeMetaServer struct {
	grpc.ServerStream
}

func (x *loggingServiceSubscribeMetaServer) Send(m *MetaResponse) error {
	return x.ServerStream.SendMsg(m)
}

// LoggingService_ServiceDesc is the grpc.ServiceDesc for LoggingService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoggingService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arista.logging.v1.LoggingService",
	HandlerType: (*LoggingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOne",
			Handler:    _LoggingService_GetOne_Handler,
		},
		{
			MethodName: "GetMeta",
			Handler:    _LoggingService_GetMeta_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSome",
			Handler:       _LoggingService_GetSome_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAll",
			Handler:       _LoggingService_GetAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _LoggingService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeMeta",
			Handler:       _LoggingService_SubscribeMeta_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "arista/logging.v1/services.gen.proto",
}

const (
	LoggingConfigService_GetOne_FullMethodName        = "/arista.logging.v1.LoggingConfigService/GetOne"
	LoggingConfigService_GetSome_FullMethodName       = "/arista.logging.v1.LoggingConfigService/GetSome"
	LoggingConfigService_GetAll_FullMethodName        = "/arista.logging.v1.LoggingConfigService/GetAll"
	LoggingConfigService_Subscribe_FullMethodName     = "/arista.logging.v1.LoggingConfigService/Subscribe"
	LoggingConfigService_GetMeta_FullMethodName       = "/arista.logging.v1.LoggingConfigService/GetMeta"
	LoggingConfigService_SubscribeMeta_FullMethodName = "/arista.logging.v1.LoggingConfigService/SubscribeMeta"
	LoggingConfigService_Set_FullMethodName           = "/arista.logging.v1.LoggingConfigService/Set"
	LoggingConfigService_SetSome_FullMethodName       = "/arista.logging.v1.LoggingConfigService/SetSome"
	LoggingConfigService_Delete_FullMethodName        = "/arista.logging.v1.LoggingConfigService/Delete"
	LoggingConfigService_DeleteSome_FullMethodName    = "/arista.logging.v1.LoggingConfigService/DeleteSome"
	LoggingConfigService_DeleteAll_FullMethodName     = "/arista.logging.v1.LoggingConfigService/DeleteAll"
)

// LoggingConfigServiceClient is the client API for LoggingConfigService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LoggingConfigServiceClient interface {
	GetOne(ctx context.Context, in *LoggingConfigRequest, opts ...grpc.CallOption) (*LoggingConfigResponse, error)
	GetSome(ctx context.Context, in *LoggingConfigSomeRequest, opts ...grpc.CallOption) (LoggingConfigService_GetSomeClient, error)
	GetAll(ctx context.Context, in *LoggingConfigStreamRequest, opts ...grpc.CallOption) (LoggingConfigService_GetAllClient, error)
	Subscribe(ctx context.Context, in *LoggingConfigStreamRequest, opts ...grpc.CallOption) (LoggingConfigService_SubscribeClient, error)
	GetMeta(ctx context.Context, in *LoggingConfigStreamRequest, opts ...grpc.CallOption) (*MetaResponse, error)
	SubscribeMeta(ctx context.Context, in *LoggingConfigStreamRequest, opts ...grpc.CallOption) (LoggingConfigService_SubscribeMetaClient, error)
	Set(ctx context.Context, in *LoggingConfigSetRequest, opts ...grpc.CallOption) (*LoggingConfigSetResponse, error)
	SetSome(ctx context.Context, in *LoggingConfigSetSomeRequest, opts ...grpc.CallOption) (LoggingConfigService_SetSomeClient, error)
	Delete(ctx context.Context, in *LoggingConfigDeleteRequest, opts ...grpc.CallOption) (*LoggingConfigDeleteResponse, error)
	DeleteSome(ctx context.Context, in *LoggingConfigDeleteSomeRequest, opts ...grpc.CallOption) (LoggingConfigService_DeleteSomeClient, error)
	DeleteAll(ctx context.Context, in *LoggingConfigDeleteAllRequest, opts ...grpc.CallOption) (LoggingConfigService_DeleteAllClient, error)
}

type loggingConfigServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLoggingConfigServiceClient(cc grpc.ClientConnInterface) LoggingConfigServiceClient {
	return &loggingConfigServiceClient{cc}
}

func (c *loggingConfigServiceClient) GetOne(ctx context.Context, in *LoggingConfigRequest, opts ...grpc.CallOption) (*LoggingConfigResponse, error) {
	out := new(LoggingConfigResponse)
	err := c.cc.Invoke(ctx, LoggingConfigService_GetOne_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggingConfigServiceClient) GetSome(ctx context.Context, in *LoggingConfigSomeRequest, opts ...grpc.CallOption) (LoggingConfigService_GetSomeClient, error) {
	stream, err := c.cc.NewStream(ctx, &LoggingConfigService_ServiceDesc.Streams[0], LoggingConfigService_GetSome_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &loggingConfigServiceGetSomeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LoggingConfigService_GetSomeClient interface {
	Recv() (*LoggingConfigSomeResponse, error)
	grpc.ClientStream
}

type loggingConfigServiceGetSomeClient struct {
	grpc.ClientStream
}

func (x *loggingConfigServiceGetSomeClient) Recv() (*LoggingConfigSomeResponse, error) {
	m := new(LoggingConfigSomeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *loggingConfigServiceClient) GetAll(ctx context.Context, in *LoggingConfigStreamRequest, opts ...grpc.CallOption) (LoggingConfigService_GetAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &LoggingConfigService_ServiceDesc.Streams[1], LoggingConfigService_GetAll_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &loggingConfigServiceGetAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LoggingConfigService_GetAllClient interface {
	Recv() (*LoggingConfigStreamResponse, error)
	grpc.ClientStream
}

type loggingConfigServiceGetAllClient struct {
	grpc.ClientStream
}

func (x *loggingConfigServiceGetAllClient) Recv() (*LoggingConfigStreamResponse, error) {
	m := new(LoggingConfigStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *loggingConfigServiceClient) Subscribe(ctx context.Context, in *LoggingConfigStreamRequest, opts ...grpc.CallOption) (LoggingConfigService_SubscribeClient, error) {
	stream, err := c.cc.NewStream(ctx, &LoggingConfigService_ServiceDesc.Streams[2], LoggingConfigService_Subscribe_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &loggingConfigServiceSubscribeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LoggingConfigService_SubscribeClient interface {
	Recv() (*LoggingConfigStreamResponse, error)
	grpc.ClientStream
}

type loggingConfigServiceSubscribeClient struct {
	grpc.ClientStream
}

func (x *loggingConfigServiceSubscribeClient) Recv() (*LoggingConfigStreamResponse, error) {
	m := new(LoggingConfigStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *loggingConfigServiceClient) GetMeta(ctx context.Context, in *LoggingConfigStreamRequest, opts ...grpc.CallOption) (*MetaResponse, error) {
	out := new(MetaResponse)
	err := c.cc.Invoke(ctx, LoggingConfigService_GetMeta_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggingConfigServiceClient) SubscribeMeta(ctx context.Context, in *LoggingConfigStreamRequest, opts ...grpc.CallOption) (LoggingConfigService_SubscribeMetaClient, error) {
	stream, err := c.cc.NewStream(ctx, &LoggingConfigService_ServiceDesc.Streams[3], LoggingConfigService_SubscribeMeta_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &loggingConfigServiceSubscribeMetaClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LoggingConfigService_SubscribeMetaClient interface {
	Recv() (*MetaResponse, error)
	grpc.ClientStream
}

type loggingConfigServiceSubscribeMetaClient struct {
	grpc.ClientStream
}

func (x *loggingConfigServiceSubscribeMetaClient) Recv() (*MetaResponse, error) {
	m := new(MetaResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *loggingConfigServiceClient) Set(ctx context.Context, in *LoggingConfigSetRequest, opts ...grpc.CallOption) (*LoggingConfigSetResponse, error) {
	out := new(LoggingConfigSetResponse)
	err := c.cc.Invoke(ctx, LoggingConfigService_Set_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggingConfigServiceClient) SetSome(ctx context.Context, in *LoggingConfigSetSomeRequest, opts ...grpc.CallOption) (LoggingConfigService_SetSomeClient, error) {
	stream, err := c.cc.NewStream(ctx, &LoggingConfigService_ServiceDesc.Streams[4], LoggingConfigService_SetSome_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &loggingConfigServiceSetSomeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LoggingConfigService_SetSomeClient interface {
	Recv() (*LoggingConfigSetSomeResponse, error)
	grpc.ClientStream
}

type loggingConfigServiceSetSomeClient struct {
	grpc.ClientStream
}

func (x *loggingConfigServiceSetSomeClient) Recv() (*LoggingConfigSetSomeResponse, error) {
	m := new(LoggingConfigSetSomeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *loggingConfigServiceClient) Delete(ctx context.Context, in *LoggingConfigDeleteRequest, opts ...grpc.CallOption) (*LoggingConfigDeleteResponse, error) {
	out := new(LoggingConfigDeleteResponse)
	err := c.cc.Invoke(ctx, LoggingConfigService_Delete_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *loggingConfigServiceClient) DeleteSome(ctx context.Context, in *LoggingConfigDeleteSomeRequest, opts ...grpc.CallOption) (LoggingConfigService_DeleteSomeClient, error) {
	stream, err := c.cc.NewStream(ctx, &LoggingConfigService_ServiceDesc.Streams[5], LoggingConfigService_DeleteSome_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &loggingConfigServiceDeleteSomeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LoggingConfigService_DeleteSomeClient interface {
	Recv() (*LoggingConfigDeleteSomeResponse, error)
	grpc.ClientStream
}

type loggingConfigServiceDeleteSomeClient struct {
	grpc.ClientStream
}

func (x *loggingConfigServiceDeleteSomeClient) Recv() (*LoggingConfigDeleteSomeResponse, error) {
	m := new(LoggingConfigDeleteSomeResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *loggingConfigServiceClient) DeleteAll(ctx context.Context, in *LoggingConfigDeleteAllRequest, opts ...grpc.CallOption) (LoggingConfigService_DeleteAllClient, error) {
	stream, err := c.cc.NewStream(ctx, &LoggingConfigService_ServiceDesc.Streams[6], LoggingConfigService_DeleteAll_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &loggingConfigServiceDeleteAllClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LoggingConfigService_DeleteAllClient interface {
	Recv() (*LoggingConfigDeleteAllResponse, error)
	grpc.ClientStream
}

type loggingConfigServiceDeleteAllClient struct {
	grpc.ClientStream
}

func (x *loggingConfigServiceDeleteAllClient) Recv() (*LoggingConfigDeleteAllResponse, error) {
	m := new(LoggingConfigDeleteAllResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LoggingConfigServiceServer is the server API for LoggingConfigService service.
// All implementations must embed UnimplementedLoggingConfigServiceServer
// for forward compatibility
type LoggingConfigServiceServer interface {
	GetOne(context.Context, *LoggingConfigRequest) (*LoggingConfigResponse, error)
	GetSome(*LoggingConfigSomeRequest, LoggingConfigService_GetSomeServer) error
	GetAll(*LoggingConfigStreamRequest, LoggingConfigService_GetAllServer) error
	Subscribe(*LoggingConfigStreamRequest, LoggingConfigService_SubscribeServer) error
	GetMeta(context.Context, *LoggingConfigStreamRequest) (*MetaResponse, error)
	SubscribeMeta(*LoggingConfigStreamRequest, LoggingConfigService_SubscribeMetaServer) error
	Set(context.Context, *LoggingConfigSetRequest) (*LoggingConfigSetResponse, error)
	SetSome(*LoggingConfigSetSomeRequest, LoggingConfigService_SetSomeServer) error
	Delete(context.Context, *LoggingConfigDeleteRequest) (*LoggingConfigDeleteResponse, error)
	DeleteSome(*LoggingConfigDeleteSomeRequest, LoggingConfigService_DeleteSomeServer) error
	DeleteAll(*LoggingConfigDeleteAllRequest, LoggingConfigService_DeleteAllServer) error
	mustEmbedUnimplementedLoggingConfigServiceServer()
}

// UnimplementedLoggingConfigServiceServer must be embedded to have forward compatible implementations.
type UnimplementedLoggingConfigServiceServer struct {
}

func (UnimplementedLoggingConfigServiceServer) GetOne(context.Context, *LoggingConfigRequest) (*LoggingConfigResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOne not implemented")
}
func (UnimplementedLoggingConfigServiceServer) GetSome(*LoggingConfigSomeRequest, LoggingConfigService_GetSomeServer) error {
	return status.Errorf(codes.Unimplemented, "method GetSome not implemented")
}
func (UnimplementedLoggingConfigServiceServer) GetAll(*LoggingConfigStreamRequest, LoggingConfigService_GetAllServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAll not implemented")
}
func (UnimplementedLoggingConfigServiceServer) Subscribe(*LoggingConfigStreamRequest, LoggingConfigService_SubscribeServer) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedLoggingConfigServiceServer) GetMeta(context.Context, *LoggingConfigStreamRequest) (*MetaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMeta not implemented")
}
func (UnimplementedLoggingConfigServiceServer) SubscribeMeta(*LoggingConfigStreamRequest, LoggingConfigService_SubscribeMetaServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeMeta not implemented")
}
func (UnimplementedLoggingConfigServiceServer) Set(context.Context, *LoggingConfigSetRequest) (*LoggingConfigSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedLoggingConfigServiceServer) SetSome(*LoggingConfigSetSomeRequest, LoggingConfigService_SetSomeServer) error {
	return status.Errorf(codes.Unimplemented, "method SetSome not implemented")
}
func (UnimplementedLoggingConfigServiceServer) Delete(context.Context, *LoggingConfigDeleteRequest) (*LoggingConfigDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedLoggingConfigServiceServer) DeleteSome(*LoggingConfigDeleteSomeRequest, LoggingConfigService_DeleteSomeServer) error {
	return status.Errorf(codes.Unimplemented, "method DeleteSome not implemented")
}
func (UnimplementedLoggingConfigServiceServer) DeleteAll(*LoggingConfigDeleteAllRequest, LoggingConfigService_DeleteAllServer) error {
	return status.Errorf(codes.Unimplemented, "method DeleteAll not implemented")
}
func (UnimplementedLoggingConfigServiceServer) mustEmbedUnimplementedLoggingConfigServiceServer() {}

// UnsafeLoggingConfigServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LoggingConfigServiceServer will
// result in compilation errors.
type UnsafeLoggingConfigServiceServer interface {
	mustEmbedUnimplementedLoggingConfigServiceServer()
}

func RegisterLoggingConfigServiceServer(s grpc.ServiceRegistrar, srv LoggingConfigServiceServer) {
	s.RegisterService(&LoggingConfigService_ServiceDesc, srv)
}

func _LoggingConfigService_GetOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoggingConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggingConfigServiceServer).GetOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoggingConfigService_GetOne_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggingConfigServiceServer).GetOne(ctx, req.(*LoggingConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoggingConfigService_GetSome_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoggingConfigSomeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoggingConfigServiceServer).GetSome(m, &loggingConfigServiceGetSomeServer{stream})
}

type LoggingConfigService_GetSomeServer interface {
	Send(*LoggingConfigSomeResponse) error
	grpc.ServerStream
}

type loggingConfigServiceGetSomeServer struct {
	grpc.ServerStream
}

func (x *loggingConfigServiceGetSomeServer) Send(m *LoggingConfigSomeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LoggingConfigService_GetAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoggingConfigStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoggingConfigServiceServer).GetAll(m, &loggingConfigServiceGetAllServer{stream})
}

type LoggingConfigService_GetAllServer interface {
	Send(*LoggingConfigStreamResponse) error
	grpc.ServerStream
}

type loggingConfigServiceGetAllServer struct {
	grpc.ServerStream
}

func (x *loggingConfigServiceGetAllServer) Send(m *LoggingConfigStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LoggingConfigService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoggingConfigStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoggingConfigServiceServer).Subscribe(m, &loggingConfigServiceSubscribeServer{stream})
}

type LoggingConfigService_SubscribeServer interface {
	Send(*LoggingConfigStreamResponse) error
	grpc.ServerStream
}

type loggingConfigServiceSubscribeServer struct {
	grpc.ServerStream
}

func (x *loggingConfigServiceSubscribeServer) Send(m *LoggingConfigStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LoggingConfigService_GetMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoggingConfigStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggingConfigServiceServer).GetMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoggingConfigService_GetMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggingConfigServiceServer).GetMeta(ctx, req.(*LoggingConfigStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoggingConfigService_SubscribeMeta_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoggingConfigStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoggingConfigServiceServer).SubscribeMeta(m, &loggingConfigServiceSubscribeMetaServer{stream})
}

type LoggingConfigService_SubscribeMetaServer interface {
	Send(*MetaResponse) error
	grpc.ServerStream
}

type loggingConfigServiceSubscribeMetaServer struct {
	grpc.ServerStream
}

func (x *loggingConfigServiceSubscribeMetaServer) Send(m *MetaResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LoggingConfigService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoggingConfigSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggingConfigServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoggingConfigService_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggingConfigServiceServer).Set(ctx, req.(*LoggingConfigSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoggingConfigService_SetSome_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoggingConfigSetSomeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoggingConfigServiceServer).SetSome(m, &loggingConfigServiceSetSomeServer{stream})
}

type LoggingConfigService_SetSomeServer interface {
	Send(*LoggingConfigSetSomeResponse) error
	grpc.ServerStream
}

type loggingConfigServiceSetSomeServer struct {
	grpc.ServerStream
}

func (x *loggingConfigServiceSetSomeServer) Send(m *LoggingConfigSetSomeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LoggingConfigService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoggingConfigDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LoggingConfigServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LoggingConfigService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LoggingConfigServiceServer).Delete(ctx, req.(*LoggingConfigDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LoggingConfigService_DeleteSome_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoggingConfigDeleteSomeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoggingConfigServiceServer).DeleteSome(m, &loggingConfigServiceDeleteSomeServer{stream})
}

type LoggingConfigService_DeleteSomeServer interface {
	Send(*LoggingConfigDeleteSomeResponse) error
	grpc.ServerStream
}

type loggingConfigServiceDeleteSomeServer struct {
	grpc.ServerStream
}

func (x *loggingConfigServiceDeleteSomeServer) Send(m *LoggingConfigDeleteSomeResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LoggingConfigService_DeleteAll_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(LoggingConfigDeleteAllRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LoggingConfigServiceServer).DeleteAll(m, &loggingConfigServiceDeleteAllServer{stream})
}

type LoggingConfigService_DeleteAllServer interface {
	Send(*LoggingConfigDeleteAllResponse) error
	grpc.ServerStream
}

type loggingConfigServiceDeleteAllServer struct {
	grpc.ServerStream
}

func (x *loggingConfigServiceDeleteAllServer) Send(m *LoggingConfigDeleteAllResponse) error {
	return x.ServerStream.SendMsg(m)
}

// LoggingConfigService_ServiceDesc is the grpc.ServiceDesc for LoggingConfigService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LoggingConfigService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "arista.logging.v1.LoggingConfigService",
	HandlerType: (*LoggingConfigServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetOne",
			Handler:    _LoggingConfigService_GetOne_Handler,
		},
		{
			MethodName: "GetMeta",
			Handler:    _LoggingConfigService_GetMeta_Handler,
		},
		{
			MethodName: "Set",
			Handler:    _LoggingConfigService_Set_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _LoggingConfigService_Delete_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSome",
			Handler:       _LoggingConfigService_GetSome_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAll",
			Handler:       _LoggingConfigService_GetAll_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Subscribe",
			Handler:       _LoggingConfigService_Subscribe_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SubscribeMeta",
			Handler:       _LoggingConfigService_SubscribeMeta_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "SetSome",
			Handler:       _LoggingConfigService_SetSome_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DeleteSome",
			Handler:       _LoggingConfigService_DeleteSome_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "DeleteAll",
			Handler:       _LoggingConfigService_DeleteAll_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "arista/logging.v1/services.gen.proto",
}
