# Copyright (c) 2016 Arista Networks, Inc.  All rights reserved.
# Arista Networks, Inc. Confidential and Proprietary.

# YAML to test for ansible configurations that we want changed
---
- hosts: all
  become: yes
  become_user: root
...
