# Copyright (c) 2016 Arista Networks, Inc.  All rights reserved.
# Arista Networks, Inc. Confidential and Proprietary.

---
- hosts: all
  tasks:
  - name: Tests all other playbooks included here.
    shell: echo 'Running playbooks for testing...'

#======= Add functionality playbooks for testing below =======
- include: ping_test.yml 
- include: updateMotd_test.yml
