# Copyright (c) 2016 Arista Networks, Inc.  All rights reserved.
# Arista Networks, Inc. Confidential and Proprietary.

---
- hosts: all
  become: yes
  become_user: root
  vars:
     updateMotd_motdPath: '/etc/motd'
     updateMotd_ansibleCfgMsg: "[ANSIBLE] This machine \"{{ansible_hostname}}\" is managed by Ansible."
     updateMotd_exprToMatch: "^[ANSIBLE]"
  tasks:
     - name: "Update /etc/motd message"
       lineinfile: 
          dest: "{{ updateMotd_motdPath }}"
          regexp: "{{ updateMotd_exprToMatch }}"
          insertbefore: BOF
          line: "{{ updateMotd_ansibleCfgMsg }}"
          create: yes

     - name: "TEST"
       script: test/test_updateMotd.sh
       when: TEST is defined
...
