---
- name: "Check that vmstat is running"
  shell: service vmstat status | grep "active"

- name: "Verify server info is available via arventory"
  shell: arventory list -l {{ansible_hostname}} | grep -q "{{ansible_hostname}}" 

- name: "Delete cron job calling ASB"
  file:
     path: /etc/cron.d/ASB
     state: absent

- name: "Update datacenter.servers with status for this machine as installed"
  command: "{{ASB_DB_UPDATE_INSTALLED}}"

- name: "Send Thomas email if this isn't a test run"
  shell: "echo \"{{ASB_MAIL_BODY}}\" | mail -s \"{{ASB_MAIL_HEADER}}\" twieland@arista.com"
  when: TESTMODE is undefined

- name: "Send mock email if this is a test run"
  shell: "echo \"{{ASB_MAIL_BODY}}\" | mail -s \"{{ASB_MAIL_HEADER}}\" ren@arista.com"
  when: TESTMODE is defined
...
